Committees:
{% if PRODUCT == '4us' %}
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    SSESpecification:
      SSEEnabled: true
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    ProvisionedThroughput:
      WriteCapacityUnits: 5
      ReadCapacityUnits: 5
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_IMAGE
{% endif %}
