type = "javascript"
account_id = "0aa021eccda30cdd219955dcafa62b13"

[env.qa]
name = "committee-redirector-qa"
zone_id = "40ed36745df172f3d0680d156899e619"
route = "donate.build4.us/*"
vars = { ENVIRONMENT = "qa" }

[env.prod]
name = "committee-redirector"
zone_id = "eecd123fc5edf71294e1b7b11525d0fc"
route = "donate.4us.net/*"
vars = { ENVIRONMENT = "prod" }

[env.demo]
name = "committee-redirector-demo"
zone_id = "b48424de46a52217d1a97d128f0fff7d"
route = "donate.4usdemo.com/*"
vars = { ENVIRONMENT = "demo" }
