AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  4us-serverless

  SAM Template for 4us-serverless

Parameters:
  PrivateSubnets:
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
    Default: /cfn/ec2/subnets/private/all
  LambdaSecurityGroup:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>
    Default: /cfn/ec2/securitygroup/lambda
  LambdaRunEnvironment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds: !Ref PrivateSubnets

Resources:
  DonorGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Models:
        Contribution:
          type: object
          required:
            - cardNumber
            - cardExpirationMonth
            - cardExpirationYear
          properties:
            firstName:
              type: string
            lastName:
              type: integer
            addressLine1:
              type: string
            addressLine2:
              type: string
            city:
              type: integer
            state:
              type: string
            postalCode:
              type: string
            cardNumber:
              type: string
            cardExpirationMonth:
              type: string
            cardExpirationYear:
              type: string
            cardCVC:
              type: string
            refCode:
              type: string
            amount:
              type: integer


  ContributeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: services/contribute/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Contribute:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /contribute
            Method: post
            RestApiId: !Ref DonorGateway
      Environment:
        Variables:
          runenv: !Ref LambdaRunEnvironment
