DynamoDBGraphQLPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
          Effect: Allow
          Resource:
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${BillableEvents}
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Transactions}
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Transactions}/index/TransactionsByCommitteeDonorIndex
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Committees}
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Donors}
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Rules}
          Action:
            - dynamodb:PartiQLSelect
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
