DynamoDBStreamReaderPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
          Effect: Allow
          Resource:
            !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Contributions}/stream/*
          Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListShards
            - dynamodb:ListStreams
