DynamoDBReadCommitteesPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Resource:
            - !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableArn
          Action:
            - dynamodb:ListShards
            - dynamodb:GetItem
