DynamoDBGraphQLPolicy:
  Type: AWS::IAM::ManagedPolicy
  DependsOn: DynamoDBsTemplate
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
          Effect: Allow
          Resource:
            - !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableArn
            - !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableArn
            - !Sub ${DynamoDBsTemplate.Outputs.TransactionsTableArn}/index/TransactionsByCommitteeDonorIndex
            - !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableArn
            - !GetAtt DynamoDBsTemplate.Outputs.DonorsTableArn
            - !GetAtt DynamoDBsTemplate.Outputs.RulesTableArn
          Action:
            - dynamodb:PartiQLSelect
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
