DynamoDBStreamReaderPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
          Effect: Allow
          Resource:
            - !GetAtt DynamoDBsTemplate.Outputs.TransactionsStream
            - !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableArn
            - !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableArn
          Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListShards
            - dynamodb:ListStreams
            - dynamodb:GetItem
