LambdaBasicPolicy:
  Type: AWS::IAM::ManagedPolicy
  Description: Policy for all Lambdas in {{ DOMAIN }}.{{ TLD }}
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: ParameterStoreParameterAccess
          Effect: Allow
          Action:
            - ssm:GetParameter*
          Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*
        - Sid: VPCNetworkInterfaces
          Effect: Allow
          Resource: '*'
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
        - Sid: BasicExecutionPolicy
          Effect: Allow
          Resource: '*'
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
        - Sid: EnableLambdaDLQ
          Effect: Allow
          Resource:
            - !Ref LambdaDLQ
            - !Ref LambdaSuccessQueue
          Action:
            - sns:Publish
