LambdaSQSPolicy:
  Type: AWS::IAM::ManagedPolicy
  DeletionPolicy: Retain
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: SendSQSNotifications
          Effect: Allow
          Action:
            - sqs:*
          Resource: '*'
