Aggregates:
  Type: AWS::DynamoDB::GlobalTable
  DeletionPolicy: Retain
  Properties:
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: committeeId
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: committeeId
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    Replicas:
    {% if RUNENV == 'prod' %}
      - Region: !Ref BackupRegion
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    {% endif %}
      - Region: !Ref AWS::Region
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
