Donors:
  Type: AWS::DynamoDB::GlobalTable
  DeletionPolicy: Retain
  Properties:
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: flacspeeMatch
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      - AttributeName: instantIdUniqueId
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: flacspeeMatch
      - KeyType: RANGE
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    GlobalSecondaryIndexes:
      - IndexName: DonorsByInstantIdUniqueId
        KeySchema:
          - KeyType: HASH
            AttributeName: instantIdUniqueId
        Projection:
          ProjectionType: ALL
    Replicas:
      - Region: !Ref AWS::Region
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
{% if RUNENV == 'prod' %}
      - Region: !Ref BackupRegion
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
{% endif %}
