Donors:
{% if PRODUCT == '4us' %}
  Type: AWS::DynamoDB::GlobalTable
  DeletionPolicy: Retain
  Properties:
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: flacspeeMatch
        AttributeType: S
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: flacspeeMatch
      - KeyType: RANGE
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_IMAGE
    Replicas:
      - Region: !Ref AWS::Region
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
{% endif %}
