Transactions:
  Type: AWS::DynamoDB::GlobalTable
  DeletionPolicy: Retain
  Properties:
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
    AttributeDefinitions:
      - AttributeName: committeeId
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      - AttributeName: donorId
        AttributeType: S
      - AttributeName: actBlueTransactionId
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: committeeId
      - KeyType: RANGE
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    GlobalSecondaryIndexes:
      - IndexName: TransactionsByCommitteeDonorIndex
        KeySchema:
          - KeyType: HASH
            AttributeName: committeeId
          - KeyType: RANGE
            AttributeName: donorId
        Projection:
          ProjectionType: ALL
      - IndexName: TransactionsByActBlueTransactionId
        KeySchema:
          - KeyType: HASH
            AttributeName: committeeId
          - KeyType: RANGE
            AttributeName: actBlueTransactionId
        Projection:
          ProjectionType: KEYS_ONLY
      - IndexName: TransactionsByExternalTransactionId
        KeySchema:
          - KeyType: HASH
            AttributeName: committeeId
          - KeyType: RANGE
            AttributeName: externalTransactionId
          Projection:
            ProjectionType: ALL
    Replicas:
      - Region: !Ref AWS::Region
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: TransactionsByCommitteeDonorIndex
{% if RUNENV == 'prod' %}
      - Region: !Ref BackupRegion
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: TransactionsByCommitteeDonorIndex
{% endif %}
