PlatformUserPool:
  Type: AWS::Cognito::UserPool
  Condition: 4US
  Properties:
    Policies:
      PasswordPolicy:
        MinimumLength: 8
    UsernameAttributes:
      - email
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    Schema:
      - AttributeDataType: String
        Name: email
        Required: false
