PlatformUserPool:
  Type: AWS::Cognito::UserPool
  Condition: 4US
  Properties:
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireNumbers: true
    UsernameAttributes:
      - email
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    Schema:
      - AttributeDataType: String
        Name: email
        Required: false
{% if RUNENV == 'prod' %}
    UserPoolAddOns:
      AdvancedSecurityMode: AUDIT
{% endif %}
