EmailQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: "ContributionsEmailQueue.fifo"
    FifoQueue: true
    ContentBasedDeduplication: true
    VisibilityTimeout: 900
    KmsMasterKeyId: alias/aws/sqs
