DynamoDBStreamReaderPolicy:
  Type: AWS::IAM::Policy
  Properties:
    Roles:
      - !Ref LambdaSESRole
    PolicyName: ReadDyanmoDBStream
    PolicyDocument:
      Version: 2012-10-17
      Statement:
          Effect: Allow
          Resource:
            !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContributionRecords}/stream/*
          Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListShards
            - dynamodb:ListStreams
