LambdaSQSManagedPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    Roles:
      - !Ref LambdaDonationReceiverRole
      - !Ref LambdaSESRole
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: SendSQSNotifications
          Effect: Allow
          Action:
            - sqs:*
          Resource: '*'
