LambdaSNSWriterPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    Roles:
      - !Ref LambdaDonationReceiverRole
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: SendSNSNotifications
          Effect: Allow
          Action:
            - sns:Publish
          Resource: '*'
