SendEmailPolicy:
  Type: AWS::IAM::Policy
  Properties:
    Roles:
      - !Ref LambdaSESRole
    PolicyName: ReadDDBStreamAndSendSESEmails
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: DynamoDBStreamReader
          Effect: Allow
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContributionRecords}/stream/*
          Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListShards
            - dynamodb:ListStreams
        - Sid: SendSESNotifications
          Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: '*'
