LambdaDonationReceiverRole:
  Type: AWS::IAM::Role
  Properties:
    ManagedPolicyArns:
      - !Ref LambdaBasicPolicy
      - !Ref LambdaKMSPolicy
      - !Ref LambdaSNSWriterPolicy
      - !Ref LambdaSQSPolicy
      - !Ref DynamoDBStreamReaderPolicy
      - !Ref DynamoDBReadCommitteesPolicy
      - !Ref DynamoDBReadTransactionsPolicy
      - !Ref DynamoDBAuditLogsPolicy
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
