# Basis for this code is from:
# https://adamj.eu/tech/2019/04/15/scoring-a+-for-security-headers-on-my-cloudfront-hosted-static-website/
LambdaEdgeFunction:
  Type: AWS::Lambda::Function
  Condition: Production
  Properties:
    Role: !GetAtt LambdaEdgeRole.Arn
    FunctionName: PurplePayHeaders
    Description: !Sub Lambda@Edge for hsts for ${Domain}
    Handler: index.handler
    MemorySize: 128
    Timeout: 1
    Runtime: nodejs12.x
    Code:
      # If updating the code, update the function version as well
      ZipFile: !Sub |
        'use strict';
        exports.handler = (event, context, callback) => {
          const response = event.Records[0].cf.response;
          const headers  = response.headers;

          headers['strict-transport-security'] = [{
            key: 'Strict-Transport-Security',
            value: 'max-age=31536000; includeSubdomains'
          }];

          headers['content-security-policy'] = [{
            key: 'Content-Security-Policy',
            value: "default-src 'self'; frame-ancestors 'none'; form-action 'self'; object-src 'none'; frame-src 'self'; child-src 'self'; script-src 'self'; script-src-elem 'self' https://connect2.finicity.com/assets/sdk/finicity-connect.min.js 'unsafe-inline'; style-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://stackpath.bootstrapcdn.com; style-src-attr 'self'; font-src 'self' https://cdnjs.cloudflare.com https://stackpath.bootstrapcdn.com https://fonts.gstatic.com; upgrade-insecure-requests;"
          }];

          headers['x-content-type-options'] = [{
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          }];

          headers['x-frame-options'] = [{
            key: 'X-Frame-Options',
            value: 'DENY'
          }];

          headers['x-xss-protection'] = [{
            key: 'X-XSS-Protection',
            value: '1; mode=block'
          }];

          headers['referrer-policy'] = [{
            key: 'Referrer-Policy',
            value: 'same-origin'
          }];

          headers['cache-control'] = [{
            key: 'Cache-Control',
            value: 'no-cache'
          }];

          headers['expect-ct'] = [{
            key: 'Expect-CT',
            value: 'max-age=86400, report-uri="${Domain}"'
          }];

          headers['server'] = [{
            key: 'Server',
            value: ''
          }];

          headers['permissions-policy'] = [{
            key: 'Permissions-Policy',
            value: 'accelerometer=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(),  geolocation=*, gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), sync-xhr=(), usb=()'
          }];

          callback(null, response);
        };
