export enum FinicityTransactionType {
  atm = "atm",
  cash = "cash",
  check = "check",
  credit = "credit",
  debit = "debit",
  deposit = "deposit",
  directDebit = "directDebit",
  directDeposit = "directDeposit",
  dividend = "dividend",
  fee = "fee",
  interest = "interest",
  other = "other",
  payment = "payment",
  pointOfSale = "pointOfSale",
  repeatPayment = "repeatPayment",
  serviceCharge = "serviceCharge",
  transfer = "transfer",
}
