export enum PurposeCode {
  LITER = "LITER",
  OFFICE = "OFFICE",
  OTHER = "OTHER",
  PETIT = "PETIT",
  INT = "INT",
  POLLS = "POLLS",
  POSTA = "POSTA",
  PRINT = "PRINT",
  PROFL = "PROFL",
  RADIO = "RADIO",
  REIMB = "REIMB",
  RDET = "RDET",
  RENTO = "RENTO",
  TVADS = "TVADS",
  VOTER = "VOTER",
  WAGES = "WAGES",
  BKFEE = "BKFEE",
  LWNSN = "LWNSN",
}
