export enum PurposeCode {
  LITER = "LITER",
  OFFICE = "OFFICE",
  OTHER = "OTHER",
  PETIT = "PETIT",
  INT = "INT",
  POLLS = "POLLS",
  POSTA = "POSTA",
  PRINT = "PRINT",
  PROFL = "PROFL",
  RADIO = "RADIO",
  REIMB = "REIMB",
  RDET = "RDET",
  RENTO = "RENTO",
  TVADS = "TVADS",
  VOTER = "VOTER",
  WAGES = "WAGES",
  BKFEE = "BKFEE",
  LWNSN = "LWNSN",
}

export const purposeCodes = [
  PurposeCode.LITER,
  PurposeCode.OFFICE,
  PurposeCode.OTHER,
  PurposeCode.PETIT,
  PurposeCode.INT,
  PurposeCode.POLLS,
  PurposeCode.POSTA,
  PurposeCode.PRINT,
  PurposeCode.PROFL,
  PurposeCode.RADIO,
  PurposeCode.REIMB,
  PurposeCode.RDET,
  PurposeCode.RENTO,
  PurposeCode.TVADS,
  PurposeCode.VOTER,
  PurposeCode.WAGES,
  PurposeCode.BKFEE,
  PurposeCode.LWNSN,
];
