CommitteeGatewayFirewall:
  Type: AWS::WAFv2::WebACL
  Condition: NonQA
  Properties:
    Name: !Sub CommitteeGatewayFirewall${LambdaRunEnvironment}
    Scope: REGIONAL
    DefaultAction:
      Allow: {}
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: !Sub WAF-${LambdaRunEnvironment}-${Product}
    Rules:
      - Name: RuleWithAWSManagedRules
        Priority: 0
        OverrideAction:
          Count: {}
        VisibilityConfig:
          MetricName: RuleWithAWSManagedRulesMetric
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesCommonRuleSet
            VendorName: AWS
            ExcludedRules: []
