CommitteeFirewallAssociation:
  Type: AWS::WAFv2::WebACLAssociation
  DependsOn: CommitteeGateway
  Condition: NonQA
  Properties:
    ResourceArn: !Sub
        arn:aws:apigateway:${AWS::Region}::/restapis/${CommitteeGateway}/stages/${LambdaRunEnvironment}
    WebACLArn: !GetAtt CommitteeGatewayFirewall.Arn
