ServicesLayer:
  Type: AWS::Serverless::LayerVersion
  Properties:
    LayerName: !Sub ${AWS::StackName}-ServicesLayer
    ContentUri: ./services
    CompatibleRuntimes:
      - nodejs14.x
  Metadata:
    BuildMethod: nodejs14.x
