EmailQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: !Sub ${LambdaRunEnvironment}-${Domain}-ReceiptEmailQueue.fifo
    FifoQueue: true
    ContentBasedDeduplication: true
    VisibilityTimeout: 900
    KmsMasterKeyId: alias/aws/sqs
