{% for site in ('dev', 'qa') %}
{{ site }}WebsiteBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    BucketName: !Sub {{ site | lower }}.${Domain}-${AWS::Region}
    AccessControl: Private
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      IgnorePublicAcls: false
      BlockPublicPolicy: true
      RestrictPublicBuckets: true
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    VersioningConfiguration:
      Status: Enabled
    ReplicationConfiguration:
      !If
        - Production
        -
          Role: !GetAtt {{ site }}WebsiteReplicationRole.Arn
          Rules:
            - Id: BackupToCalifornia
              Status: Enabled
              Destination:
                Bucket: !Sub arn:aws:s3:::{{ site | lower }}.${Domain}-us-west-1
                StorageClass: STANDARD
              Prefix: ''
              #SourceSelectionCriteria:
              # ReplicaModifications:
              #   Status: Enabled
              # SseKmsEncryptedObjects:
              #   Status: Enabled
        - !Ref AWS::NoValue
{{ site }}WebsiteBucketPolicy:
  Type: AWS::S3::BucketPolicy
  {% if REGION == 'us-east-1' %}DependsOn: OAIPurplePay{% endif %}
  Properties:
    Bucket: !Ref {{ site }}WebsiteBucket
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: AlloWSSLRequestsOnly
          Effect: Deny
          Resource:
            - !GetAtt {{ site }}WebsiteBucket.Arn
            - !Join
                - '/'
                - - !GetAtt {{ site }}WebsiteBucket.Arn
                  - '*'
          Action: s3:*
          Condition:
            Bool:
              aws:SecureTransport: false
          Principal: '*'
  {% if REGION == 'us-east-1' %}
        - Sid: AllowCloudFrontAccess
          Effect: Allow
          Resource:
            !Join 
              - '/'
              - - !GetAtt {{ site }}WebsiteBucket.Arn
                - '*'
          Action: s3:GetObject
          Principal:
            AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAIPurplePay}
  {% endif %}
{% endfor %}
