CommitteeGateway:
  Type: AWS::Serverless::Api
  Properties:
    Name: !Sub ${AWS::StackName}-committee
    StageName: !Sub ${LambdaRunEnvironment}
    Domain:
      CertificateArn: !Ref CertificateManagerCertificate
      DomainName: !Sub committee-api.${Domain}.${TLD}
      EndpointConfiguration: REGIONAL
      Route53:
        EvaluateTargetHealth: true
        HostedZoneId: !Ref HostedZone
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: '/*'
        HttpMethod: '*'
    Auth:
      DefaultAuthorizer: PlatformUserCognitoAuthorizer
      Authorizers:
        PlatformUserCognitoAuthorizer:
        {% if PRODUCT == '4us' %}
          UserPoolArn: !GetAtt PlatformUserPool.Arn
        {% else %}
          UserPoolArn: !Ref PlatformUserPoolArn
        {% endif %}
