CommitteeGateway:
  Type: AWS::Serverless::Api
  Properties:
    Name: !Sub ${AWS::StackName}-committee
    StageName: !Sub ${LambdaRunEnvironment}
    Domain:
      CertificateArn: !Ref CertificateManagerCertificate
      DomainName: !Sub capi{% if RUNENV != 'prod' %}-${LambdaRunEnvironment}{% endif %}.${Domain}.${TLD}
      EndpointConfiguration: REGIONAL
      Route53:
        EvaluateTargetHealth: true
        HostedZoneId: !Ref HostedZone
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: '/*'
        HttpMethod: '*'
    Auth:
      #AddDefaultAuthorizerToCorsPreflight: true
      DefaultAuthorizer: PlatformUserCognitoAuthorizer
      Authorizers:
        PlatformUserCognitoAuthorizer:
          UserPoolArn: !GetAtt PlatformUserCognitoUserPool.Arn
