DonationGateway:
  Type: AWS::Serverless::Api
  Properties:
    Name: !Sub ${AWS::StackName}-donation
    StageName: !Sub ${LambdaRunEnvironment}
    Domain:
      CertificateArn: !Ref CertificateManagerCertificate
      DomainName: !Sub donor-api-${LambdaRunEnvironment}.${Domain}.${TLD}
      EndpointConfiguration: REGIONAL
      DistributionDomainName: !Sub donate-${LambdaRunEnvironment}.${Domain}.${TLD}
      Route53:
        EvaluateTargetHealth: true
        HostedZoneId: !Ref HostedZone
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: '/*'
        HttpMethod: '*'
    Models:
      Contribution:
        type: object
        required:
          - cardNumber
          - cardExpirationMonth
          - cardExpirationYear
        properties:
          firstName:
            type: string
          lastName:
            type: string
          addressLine1:
            type: string
          addressLine2:
            type: string
          city:
            type: string
          state:
            type: string
          postalCode:
            type: string
          cardNumber:
            type: string
          cardExpirationMonth:
            type: string
          cardExpirationYear:
            type: string
          cardCVC:
            type: string
          refCode:
            type: string
          amount:
            type: integer
