DonorGateway:
  Type: AWS::Serverless::Api
  Properties:
    Name: !Sub ${AWS::StackName}-donation
    StageName: !Sub ${LambdaRunEnvironment}
    TracingEnabled: true
    Domain:
      CertificateArn: !Ref CertificateManagerCertificate
      DomainName: !Sub donate-api.${Domain}.${TLD}
      EndpointConfiguration: REGIONAL
      SecurityPolicy: TLS_1_2
    Cors:
      AllowCredentials: true
      AllowOrigin: "'https://dashboard.{{ DOMAIN }}.{{ TLD }}'"
      AllowMethods: "'OPTIONS,GET,PUT,POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'https://dashboard.{{ DOMAIN }}.{{ TLD }}'"
#        ResponseTemplates:
#          "application/json": "{ \"message\": 4xx error }"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'https://dashboard.{{ DOMAIN }}.{{ TLD }}'"
#        ResponseTemplates:
#          "application/json": "{ \"message\": 5xx error }"
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: '/*'
        HttpMethod: '*'
        CacheDataEncrypted: true
        MetricsEnabled: true
        DataTraceEnabled: true
    Models:
      Contribution:
        type: object
        required:
          - cardNumber
          - cardExpirationMonth
          - cardExpirationYear
        properties:
          firstName:
            type: string
          lastName:
            type: string
          addressLine1:
            type: string
          addressLine2:
            type: string
          city:
            type: string
          state:
            type: string
          postalCode:
            type: string
          cardNumber:
            type: string
          cardExpirationMonth:
            type: string
          cardExpirationYear:
            type: string
          cardCVC:
            type: string
          refCode:
            type: string
          amount:
            type: integer
