import { ICommittee } from "../../src/queries/get-committee-by-id.query";
import { Plan } from "../../src/utils/enums/plan.enum";

export const committeesData: ICommittee[] = [
  {
    // required
    id: "angel-cruz",
    committeeName: "Angel Cruz for Bronx Judge",
    bankName: "other bank",
    candidateFirstName: "Angel",
    candidateLastName: "Cruz",
    stripeAccount: "acct_1IjTcsRC8iiQex3V",
    emailAddresses: "evan@schweitzerlabs.com,seemant@schweitzerlabs.com",
    platformPlan: Plan.FourUs,
    members: [
      "james-martin",
      "1643f48e-431c-4461-b2cb-b8fce4c939df",
      "c8eb897e-cd22-4dda-a4a0-2f3165024d72",
    ],
    tzDatabaseName: "America/New_York",
    state: "ny",
    scope: "state",
    party: "democrat",
    race: "general",
    district: "35",
    county: "",
    officeType: "assembly",
    ruleVersion: "nyboe-2020",
  },
  {
    // required
    id: "john-safford",
    committeeName: "John Safford for Supervisor",
    bankName: "adirondack trust company",
    candidateFirstName: "John",
    candidateLastName: "Safford",
    stripeAccount: "acct_1IjTcsRC8iiQex3V",
    emailAddresses: "evan@schweitzerlabs.com,seemant@schweitzerlabs.com",
    platformPlan: Plan.FourUs,
    members: [
      "james-martin",
      "1643f48e-431c-4461-b2cb-b8fce4c939df",
      "c8eb897e-cd22-4dda-a4a0-2f3165024d72",
    ],
    tzDatabaseName: "America/New_York",
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    finicityCustomerId: "5005871881",
    finicityAccountId: "5012575024",
  },
  {
    // required
    id: "will-schweitzer",
    committeeName: "Will Schweitzer for Supervisor",
    bankName: "chase",
    candidateFirstName: "Will",
    candidateLastName: "Schweitzer",
    stripeAccount: "acct_1IjTcsRC8iiQex3V",
    emailAddresses: "evan@schweitzerlabs.com,seemant@schweitzerlabs.com",
    platformPlan: Plan.FourUs,
    members: [
      "james-martin",
      "1643f48e-431c-4461-b2cb-b8fce4c939df",
      "c8eb897e-cd22-4dda-a4a0-2f3165024d72",
    ],
    tzDatabaseName: "America/New_York",
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    finicityCustomerId: "5007489410",
    finicityAccountId: "5016000964",
  },
  {
    // required
    id: "evan-piro",
    committeeName: "Evan Piro for Mayor",
    bankName: "chase",
    candidateFirstName: "Evan",
    candidateLastName: "Piro",
    stripeAccount: "acct_1IjTcsRC8iiQex3V",
    emailAddresses: "evan@schweitzerlabs.com",
    platformPlan: Plan.FourUs,
    members: [
      "james-martin",
      "1643f48e-431c-4461-b2cb-b8fce4c939df",
      "c8eb897e-cd22-4dda-a4a0-2f3165024d72",
    ],
    tzDatabaseName: "America/New_York",
    state: "ny",
    scope: "state",
    party: "democrat",
    race: "general",
    district: "35",
    county: "",
    officeType: "assembly",
    ruleVersion: "nyboe-2020",
    finicityCustomerId: "5003896371",
    finicityAccountId: "5015365202",
  },
];
