import { ITransaction } from "../../src/queries/search-transactions.decoder";
import { v4 as uuidv4 } from "uuid";
import { now } from "../../src/utils/time.utils";

export const disbursementsData: ITransaction[] = [
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 1000,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 12000,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 123000,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 49000,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 194000,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
  {
    id: uuidv4(),
    committeeId: "907b427a-f8a9-450b-9d3c-33d8ec4a4cc4",
    direction: "out",
    amount: 1500,
    paymentMethod: "ach",
    bankVerified: true,
    ruleVerified: false,
    initiatedTimestamp: now(),
    transactionType: "disbursement",
  },
];
