export const rulesData = [
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "fam",
    limit: 149475,
    aggregate_duration: "aggregate_limit",
    fields: "donor_full_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "ind",
    limit: 298950,
    aggregate_duration: "",
    fields: "donor_full_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "solep",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "part",
    limit: 298950,
    aggregate_duration: "",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "corp",
    limit: 500000,
    aggregate_duration: "calendar_year",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "comm",
    limit: 500000,
    aggregate_duration: "",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "union",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "assoc",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "llc",
    limit: 298950,
    aggregate_duration: "calendar_year",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "pac",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "entity_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "plc",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "donor_full_name,donor_address",
    id: 1,
  },
  {
    state: "ny",
    scope: "local",
    party: "republican",
    race: "general",
    district: "",
    county: "saratoga",
    officeType: "supervisor",
    ruleVersion: "nyboe-2020",
    contributor_type: "oth",
    limit: 298950,
    aggregate_duration: "aggregate_limit",
    fields: "donor_full_name,donor_address",
    id: 1,
  },
];
