import { ITransaction } from "../../src/queries/search-transactions.decoder";

export const unverifiedContributionsData: ITransaction[] = [
  {
    amount: 50,
    source: "dashboard",
    id: "1624474430943-F5ugpy",
    committeeId: "will-schweitzer",
    firstName: "Ralph",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624474430943,
    lastName: "Higgins",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J5bCqEUhH8cxK5gkS9f5xDl",
    cardNumberLastFourDigits: "4465",
    donorId: "1624474427182-E5ireB",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J5bCsEUhH8cxK5goCRhiMwx",
    stripeChargeId: "ch_1J5bCqEUhH8cxK5ghJrRnsLy",
    stripeTransferId: "tr_1J5bCrEUhH8cxK5gbEVvGNmy",
    stripePaymentId: "py_1J5bCrRNcAftf9zRLdmTYEki",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624396460416-sspWuq",
    committeeId: "will-schweitzer",
    firstName: "Sam",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624396460416,
    lastName: "Williams",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J5GvGEUhH8cxK5gcqJ9Giwq",
    cardNumberLastFourDigits: "4465",
    donorId: "1624396456959-PnaTSc",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J5GvHEUhH8cxK5gQA1MXe47",
    stripeChargeId: "ch_1J5GvGEUhH8cxK5gjhVO7hkj",
    stripeTransferId: "tr_1J5GvHEUhH8cxK5g1JRWMkPf",
    stripePaymentId: "py_1J5GvHRNcAftf9zRehel5WSU",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624395355651-SCprZ5",
    committeeId: "will-schweitzer",
    firstName: "Dane",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624395355651,
    lastName: "Princeton",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J5GdQEUhH8cxK5gxUls5v73",
    cardNumberLastFourDigits: "4465",
    donorId: "1624395351317-NjkVne",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J5GdTEUhH8cxK5gNbw5as0v",
    stripeChargeId: "ch_1J5GdQEUhH8cxK5giyJXftzI",
    stripeTransferId: "tr_1J5GdSEUhH8cxK5gQd4HTYht",
    stripePaymentId: "py_1J5GdSRNcAftf9zRMEFm4rk9",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624309521536-HAY4Cv",
    committeeId: "will-schweitzer",
    firstName: "Chris",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624309521536,
    lastName: "Hansen",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J4uJ0EUhH8cxK5gX1ojtVTw",
    cardNumberLastFourDigits: "4465",
    donorId: "1624309517850-f9hPCj",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J4uJ3EUhH8cxK5gbbZtiouJ",
    stripeChargeId: "ch_1J4uJ1EUhH8cxK5gxycWQ0KJ",
    stripeTransferId: "tr_1J4uJ2EUhH8cxK5gIqwop8JX",
    stripePaymentId: "py_1J4uJ2RNcAftf9zRgtmS1kZk",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624308220920-5XN78K",
    committeeId: "will-schweitzer",
    firstName: "Steve",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624308220920,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J4ty2EUhH8cxK5gR3a2pU1k",
    cardNumberLastFourDigits: "4465",
    donorId: "1624122358904-7EgYEQ",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J4ty4EUhH8cxK5gE09Y3rN0",
    stripeChargeId: "ch_1J4ty2EUhH8cxK5gIRF9tAt4",
    stripeTransferId: "tr_1J4ty3EUhH8cxK5gNHHCa8Of",
    stripePaymentId: "py_1J4ty3RNcAftf9zRtvPZyjxZ",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624295212911-2pWRcF",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624295212911,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J4qaDEUhH8cxK5gDSluOUCs",
    cardNumberLastFourDigits: "4465",
    donorId: "1624295208961-uh1Eco",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J4qaGEUhH8cxK5gtY9fkXZm",
    stripeChargeId: "ch_1J4qaEEUhH8cxK5gRUDjN1GC",
    stripeTransferId: "tr_1J4qaFEUhH8cxK5gm6GruF7l",
    stripePaymentId: "py_1J4qaFRNcAftf9zRe2ewP6eQ",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624122363411-BlYarn",
    committeeId: "will-schweitzer",
    firstName: "Steve",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624122363411,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J47cJEUhH8cxK5gLfSHqCap",
    cardNumberLastFourDigits: "4465",
    donorId: "1624122358904-7EgYEQ",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J47cMEUhH8cxK5ga6ZTfY3R",
    stripeChargeId: "ch_1J47cKEUhH8cxK5gZamnlDnD",
    stripeTransferId: "tr_1J47cMEUhH8cxK5gOugNqKbj",
    stripePaymentId: "py_1J47cMRNcAftf9zRxJR6SLus",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624048389011-9WaZPg",
    committeeId: "will-schweitzer",
    firstName: "Ryan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624048389011,
    lastName: "Manning",
    addressLine1: "139 Adrianna Squares",
    addressLine2: "Apt. 382",
    city: "New Sadiechester",
    state: "wi",
    postalCode: "69405",
    employer: "Technician",
    occupation: "Pharma",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3oNCEUhH8cxK5gOgPsmq24",
    cardNumberLastFourDigits: "4465",
    donorId: "1624048385329-mywoVZ",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3oNEEUhH8cxK5gTuA22tZs",
    stripeChargeId: "ch_1J3oNCEUhH8cxK5gX4TeZkfm",
    stripeTransferId: "tr_1J3oNEEUhH8cxK5gIWUKSoB6",
    stripePaymentId: "py_1J3oNERNcAftf9zRW1MUODYv",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624026550161-7Go7uZ",
    committeeId: "will-schweitzer",
    firstName: "Francis",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624026550161,
    lastName: "Truman",
    addressLine1: "123 Age Street",
    addressLine2: "2FL",
    city: "Brewerville",
    state: "ky",
    postalCode: "34882",
    employer: "Google",
    occupation: "Info Sec",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3igxEUhH8cxK5g29lIFGPb",
    cardNumberLastFourDigits: "4465",
    donorId: "1624026546516-o8TXeb",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3igzEUhH8cxK5gT8lcmSw8",
    stripeChargeId: "ch_1J3igxEUhH8cxK5gYSwlNdem",
    stripeTransferId: "tr_1J3igzEUhH8cxK5gVgUB9KXa",
    stripePaymentId: "py_1J3igzRNcAftf9zRmSGfPLc6",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1624026113230-EZi5BA",
    committeeId: "will-schweitzer",
    firstName: "Roger",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1624026113230,
    lastName: "Rodriguez",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    employer: "Software Engineer",
    occupation: "Principia Maths",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3iZuEUhH8cxK5g6qAJTpo7",
    cardNumberLastFourDigits: "4465",
    donorId: "1624026109465-XILLbb",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3iZwEUhH8cxK5gTATwpucD",
    stripeChargeId: "ch_1J3iZuEUhH8cxK5g4Vk1RmbY",
    stripeTransferId: "tr_1J3iZwEUhH8cxK5gZIm0uvLI",
    stripePaymentId: "py_1J3iZwRNcAftf9zRZ1lWXK2S",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1623984851349-2owd3n",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623984851349,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Solep",
    entityName: "McDonna Dental",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3XqOEUhH8cxK5gbfhHsC32",
    cardNumberLastFourDigits: "4465",
    donorId: "1623984847836-Rk8zr9",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3XqQEUhH8cxK5g3NWxIVrH",
    stripeChargeId: "ch_1J3XqPEUhH8cxK5gf1KcMcJG",
    stripeTransferId: "tr_1J3XqQEUhH8cxK5goQkfo8ya",
    stripePaymentId: "py_1J3XqQRNcAftf9zRVzlPCaRI",
  },
  {
    amount: 50,
    source: "dashboard",
    id: "1623984094700-PAqPAs",
    committeeId: "will-schweitzer",
    firstName: "Charles",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623984094700,
    lastName: "Hubburd",
    addressLine1: "139 Adrianna Squares",
    addressLine2: "Apt. 382",
    city: "New Sadiechester",
    state: "wi",
    postalCode: "69405",
    entityType: "Assoc",
    entityName: "Peoples Association",
    emailAddress: "dev.evanpiro@gmail.com",
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3XeBEUhH8cxK5gzThXoMfv",
    cardNumberLastFourDigits: "4465",
    donorId: "1623984090931-hHakUV",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3XeEEUhH8cxK5gOwWMvu1Q",
    stripeChargeId: "ch_1J3XeCEUhH8cxK5g7bLaeXUn",
    stripeTransferId: "tr_1J3XeDEUhH8cxK5gLnjoeQ3m",
    stripePaymentId: "py_1J3XeDRNcAftf9zRXHwWcb9T",
  },
  {
    amount: 200,
    source: "dashboard",
    id: "1623943881807-iAJ6kH",
    committeeId: "will-schweitzer",
    firstName: "Henry",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623943881807,
    lastName: "Miller",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3NBbEUhH8cxK5gWZFUpA39",
    cardNumberLastFourDigits: "4465",
    donorId: "1623943878163-KEJlI3",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J3NBdEUhH8cxK5gdwmEH7pW",
    stripeChargeId: "ch_1J3NBbEUhH8cxK5gadSNv2Ut",
    stripeTransferId: "tr_1J3NBcEUhH8cxK5g0HHVMfMH",
    stripePaymentId: "py_1J3NBcRNcAftf9zRQHNGmQmY",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623925953142-8ANLCd",
    committeeId: "will-schweitzer",
    firstName: "Amy",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623925953142,
    lastName: "Maclachlan",
    addressLine1: "1363 Pennsridge Place",
    city: "Downingtown",
    state: "pa",
    postalCode: "19335",
    employer: "Head of Operations",
    occupation: "Affusion Inc",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3IWQEUhH8cxK5gaflEiFf7",
    cardNumberLastFourDigits: "4465",
    donorId: "1623925949657-myPhcX",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J3IWSEUhH8cxK5gxbYCaNjm",
    stripeChargeId: "ch_1J3IWREUhH8cxK5g6l2LTz6K",
    stripeTransferId: "tr_1J3IWSEUhH8cxK5ggocErueg",
    stripePaymentId: "py_1J3IWSRNcAftf9zRAixF1TZ4",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623857818955-dVroQV",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623857818955,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Pac",
    entityName: "Political Engineers PAC",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J30nUEUhH8cxK5g6BOwKNDU",
    cardNumberLastFourDigits: "4465",
    donorId: "1623857815383-5GaLRg",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J30nWEUhH8cxK5gpdyqQR3X",
    stripeChargeId: "ch_1J30nUEUhH8cxK5gcPsHdEWr",
    stripeTransferId: "tr_1J30nWEUhH8cxK5gb2YPsQ2O",
    stripePaymentId: "py_1J30nWRNcAftf9zROq4EnDVR",
  },
  {
    source: "dashboard",
    amount: 52,
    id: "1623857651298-GZQxSK",
    committeeId: "will-schweitzer",
    firstName: "Robert",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623857651298,
    lastName: "Parish",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    employer: "Nasdaq",
    occupation: "Trader",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J30kmEUhH8cxK5gFnmDLo6M",
    cardNumberLastFourDigits: "4465",
    donorId: "1623857647090-5H72bE",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J30koEUhH8cxK5gPYTOWjL7",
    stripeChargeId: "ch_1J30kmEUhH8cxK5gWihA5mfp",
    stripeTransferId: "tr_1J30koEUhH8cxK5gTsmzYBp0",
    stripePaymentId: "py_1J30koRNcAftf9zRqrEVdvLE",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623791119467-TIiWCS",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623791119467,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Solep",
    entityName: "Raymond Cardiology",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2jReEUhH8cxK5g4zaCYC7f",
    cardNumberLastFourDigits: "4465",
    donorId: "1623791113773-WArvi7",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J2jRiEUhH8cxK5gnHO9vdcc",
    stripeChargeId: "ch_1J2jRfEUhH8cxK5gy4M427t3",
    stripeTransferId: "tr_1J2jRiEUhH8cxK5gQ9IgXj6w",
    stripePaymentId: "py_1J2jRiRNcAftf9zR5pUw1Iuq",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623790786500-fNnUsp",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623790786500,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Corp",
    entityName: "Giant Corp",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2jMKEUhH8cxK5g91kHZMZy",
    cardNumberLastFourDigits: "4465",
    donorId: "1623790783222-Fzbsnx",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J2jMMEUhH8cxK5gOvN27toX",
    stripeChargeId: "ch_1J2jMKEUhH8cxK5gF1A29nIF",
    stripeTransferId: "tr_1J2jMLEUhH8cxK5ga34EwYsM",
    stripePaymentId: "py_1J2jMLRNcAftf9zRGYWXYdfK",
  },
  {
    source: "dashboard",
    amount: 51,
    id: "1623788408301-aZ4D7q",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623788408301,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Union",
    entityName: "United Workers Union",
    emailAddress: "evanpirollc@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2ijwEUhH8cxK5gimf7PdRr",
    cardNumberLastFourDigits: "4465",
    donorId: "1623788403741-7sNZBb",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J2ijzEUhH8cxK5gW8OQ3JKv",
    stripeChargeId: "ch_1J2ijxEUhH8cxK5gPkOFw03f",
    stripeTransferId: "tr_1J2ijyEUhH8cxK5gEtsI9e9x",
    stripePaymentId: "py_1J2ijyRNcAftf9zRHm2yz7gk",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623785261593-gDs7Ci",
    committeeId: "will-schweitzer",
    firstName: "Austin",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623785261593,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Fam",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2hvCEUhH8cxK5gZmGw0JaU",
    cardNumberLastFourDigits: "4465",
    donorId: "1623785257144-dRjQmi",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J2hvFEUhH8cxK5g7PpwAMTO",
    stripeChargeId: "ch_1J2hvCEUhH8cxK5gpkY5cdOy",
    stripeTransferId: "tr_1J2hvEEUhH8cxK5gg50FgXov",
    stripePaymentId: "py_1J2hvERNcAftf9zRlImiXH06",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623783485024-vXeeqw",
    committeeId: "will-schweitzer",
    firstName: "August",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623783485024,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2hSXEUhH8cxK5gW172DxZI",
    cardNumberLastFourDigits: "4465",
    donorId: "1623783480098-wNKce9",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J2hSaEUhH8cxK5g4RcLBd7h",
    stripeChargeId: "ch_1J2hSXEUhH8cxK5gGh8MGTCb",
    stripeTransferId: "tr_1J2hSZEUhH8cxK5gPqRsOFPo",
    stripePaymentId: "py_1J2hSZRNcAftf9zRQgl4BegY",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623367656393-ERmrbu",
    committeeId: "will-schweitzer",
    firstName: "William",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623367656393,
    lastName: "Schweitzer",
    addressLine1: "355 South End Ave.",
    addressLine2: "31F",
    city: "New York",
    state: "ny",
    postalCode: "10280",
    employer: "Schweitzer Laboratories",
    occupation: "CEO",
    entityType: "Ind",
    emailAddress: "williamkschweitzer@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0xHdEUhH8cxK5gBFD2beSe",
    cardNumberLastFourDigits: "4465",
    donorId: "1623367610942-LmvYrQ",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J0xHfEUhH8cxK5gfm7TvCJb",
    stripeChargeId: "ch_1J0xHdEUhH8cxK5gi1ChK4L0",
    stripeTransferId: "tr_1J0xHfEUhH8cxK5g7k77LGug",
    stripePaymentId: "py_1J0xHfRNcAftf9zRqpf48kYF",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623360478786-ANuWKu",
    committeeId: "will-schweitzer",
    firstName: "Seemant",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623360478786,
    lastName: "Kulleen",
    addressLine1: "655 3rd St",
    addressLine2: "#42",
    city: "Oakland",
    state: "ca",
    postalCode: "94607",
    entityType: "Ind",
    emailAddress: "seemantk@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0vPrEUhH8cxK5gavlhEUXQ",
    cardNumberLastFourDigits: "4465",
    donorId: "1623360474280-TU757G",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J0vPuEUhH8cxK5gRFndbJde",
    stripeChargeId: "ch_1J0vPsEUhH8cxK5gKotIFxKv",
    stripeTransferId: "tr_1J0vPtEUhH8cxK5gdpvU9aHv",
    stripePaymentId: "py_1J0vPtRNcAftf9zRlY6EkBNG",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623359177376-KxZxvq",
    committeeId: "will-schweitzer",
    firstName: "Hans",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623359177376,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0v4sEUhH8cxK5gWqWnRuuY",
    cardNumberLastFourDigits: "4465",
    donorId: "1623359173283-DYApFK",
    employmentStatus: "Unemployed",
    stripeBalanceTransactionId: "txn_1J0v4uEUhH8cxK5gj9CGDPtO",
    stripeChargeId: "ch_1J0v4sEUhH8cxK5go9iy7W93",
    stripeTransferId: "tr_1J0v4uEUhH8cxK5gaZiQJsFB",
    stripePaymentId: "py_1J0v4uRNcAftf9zRBxMm6yZy",
  },
  {
    source: "dashboard",
    amount: 50,
    id: "1623358289574-hP2MZe",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623358289574,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    employer: "Schweitzer Labs",
    occupation: "CTO",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0uqZEUhH8cxK5gAuXCzJaB",
    cardNumberLastFourDigits: "4465",
    donorId: "1623358285935-mRvkBn",
    employmentStatus: "Employed",
    stripeBalanceTransactionId: "txn_1J0uqbEUhH8cxK5gm4GtnFNo",
    stripeChargeId: "ch_1J0uqZEUhH8cxK5gKXklDlVJ",
    stripeTransferId: "tr_1J0uqaEUhH8cxK5gzdZSV408",
    stripePaymentId: "py_1J0uqaRNcAftf9zRXft5WuWT",
  },
];
