import { ITransaction } from "../../src/queries/search-transactions.decoder";

export const unverifiedContributionsData: ITransaction[] = [
  {
    source: "donate_form",
    amount: 50,
    id: "1623925953142-8ANLCd",
    committeeId: "will-schweitzer",
    firstName: "Amy",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623925953142,
    lastName: "Maclachlan",
    addressLine1: "1363 Pennsridge Place",
    city: "Downingtown",
    state: "pa",
    postalCode: "19335",
    employer: "Head of Operations",
    occupation: "Affusion Inc",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J3IWQEUhH8cxK5gaflEiFf7",
    cardNumberLastFourDigits: "4465",
    donorId: "1623925949657-myPhcX",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623857818955-dVroQV",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623857818955,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Pac",
    entityName: "Political Engineers PAC",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J30nUEUhH8cxK5g6BOwKNDU",
    cardNumberLastFourDigits: "4465",
    donorId: "1623857815383-5GaLRg",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 52,
    id: "1623857651298-GZQxSK",
    committeeId: "will-schweitzer",
    firstName: "Robert",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623857651298,
    lastName: "Parish",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    employer: "Nasdaq",
    occupation: "Trader",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J30kmEUhH8cxK5gFnmDLo6M",
    cardNumberLastFourDigits: "4465",
    donorId: "1623857647090-5H72bE",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623791119467-TIiWCS",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623791119467,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Solep",
    entityName: "Raymond Cardiology",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2jReEUhH8cxK5g4zaCYC7f",
    cardNumberLastFourDigits: "4465",
    donorId: "1623791113773-WArvi7",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623790786500-fNnUsp",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623790786500,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Corp",
    entityName: "Giant Corp",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2jMKEUhH8cxK5g91kHZMZy",
    cardNumberLastFourDigits: "4465",
    donorId: "1623790783222-Fzbsnx",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 51,
    id: "1623788408301-aZ4D7q",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623788408301,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Union",
    entityName: "United Workers Union",
    emailAddress: "evanpirollc@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2ijwEUhH8cxK5gimf7PdRr",
    cardNumberLastFourDigits: "4465",
    donorId: "1623788403741-7sNZBb",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623785261593-gDs7Ci",
    committeeId: "will-schweitzer",
    firstName: "Austin",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623785261593,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Fam",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2hvCEUhH8cxK5gZmGw0JaU",
    cardNumberLastFourDigits: "4465",
    donorId: "1623785257144-dRjQmi",
    employmentStatus: "Unemployed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623783485024-vXeeqw",
    committeeId: "will-schweitzer",
    firstName: "August",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623783485024,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Fam",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J2hSXEUhH8cxK5gW172DxZI",
    cardNumberLastFourDigits: "4465",
    donorId: "1623783480098-wNKce9",
    employmentStatus: "Unemployed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623367656393-ERmrbu",
    committeeId: "will-schweitzer",
    firstName: "William",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623367656393,
    lastName: "Schweitzer",
    addressLine1: "355 South End Ave.",
    addressLine2: "31F",
    city: "New York",
    state: "ny",
    postalCode: "10280",
    employer: "Schweitzer Laboratories",
    occupation: "CEO",
    entityType: "Ind",
    emailAddress: "williamkschweitzer@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0xHdEUhH8cxK5gBFD2beSe",
    cardNumberLastFourDigits: "4465",
    donorId: "1623367610942-LmvYrQ",
    employmentStatus: "Employed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623360478786-ANuWKu",
    committeeId: "will-schweitzer",
    firstName: "Seemant",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623360478786,
    lastName: "Kulleen",
    addressLine1: "655 3rd St",
    addressLine2: "#42",
    city: "Oakland",
    state: "ca",
    postalCode: "94607",
    entityType: "Ind",
    emailAddress: "seemantk@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0vPrEUhH8cxK5gavlhEUXQ",
    cardNumberLastFourDigits: "4465",
    donorId: "1623360474280-TU757G",
    employmentStatus: "Unemployed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623359177376-KxZxvq",
    committeeId: "will-schweitzer",
    firstName: "Hans",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623359177376,
    lastName: "Piro",
    addressLine1: "448 Stockholm St",
    addressLine2: "2fl",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    entityType: "Ind",
    emailAddress: "evan@schweitzerlabs.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0v4sEUhH8cxK5gWqWnRuuY",
    cardNumberLastFourDigits: "4465",
    donorId: "1623359173283-DYApFK",
    employmentStatus: "Unemployed",
  },
  {
    source: "donate_form",
    amount: 50,
    id: "1623358289574-hP2MZe",
    committeeId: "will-schweitzer",
    firstName: "Evan",
    direction: "In",
    paymentMethod: "Credit",
    bankVerified: false,
    ruleVerified: true,
    initiatedTimestamp: 1623358289574,
    lastName: "Piro",
    addressLine1: "1687 Gates Ave 1R",
    city: "Ridgewood",
    state: "ny",
    postalCode: "11385",
    employer: "Schweitzer Labs",
    occupation: "CTO",
    entityType: "Ind",
    emailAddress: "dev.evanpiro@gmail.com",
    attestsToBeingAnAdultCitizen: true,
    transactionType: "Contribution",
    stripePaymentIntentId: "pi_1J0uqZEUhH8cxK5gAuXCzJaB",
    cardNumberLastFourDigits: "4465",
    donorId: "1623358285935-mRvkBn",
    employmentStatus: "Employed",
  },
];
