SQSDLQ:
  Type: AWS::SSM::Parameter::Value<String>
  Default: /{{ RUNENV }}/{{ PRODUCT }}/sqs/fifo/dlq

LambdaDLQ:
  Type: AWS::SSM::Parameter::Value<String>
  Default: /{{ RUNENV }}/{{ PRODUCT }}/sns/dlq

LambdaSuccessQueue:
  Type: AWS::SSM::Parameter::Value<String>
  Default: /{{ RUNENV }}/{{ PRODUCT }}/sns/successq

