TLD:
  Type: String
  Default: {{ TLD }}
Domain:
  Type: String
  Default: {{ DOMAIN }}
SubDomain:
  Type: String
  Default: {{ SUBDOMAIN }}
HostedZone:
  Type: AWS::SSM::Parameter::Value<String>
  Default: /cfn/route53/hostedzone/{{ DOMAIN }}
CertificateManagerCertificate:
  Type: AWS::SSM::Parameter::Value<String>
  Default: /cfn/ACM/Certificate/{{ DOMAIN }}
