UserPoolUserTracey:
  Type: AWS::Cognito::UserPoolUser
  Condition: Demo
  Properties:
    Username: tracey@civica.law
    UserPoolId: !Ref PlatformUserPool
    UserAttributes:
      - Name: email_verified
        Value: 'true'
      - Name: email
        Value: tracey@civica.law
