DonationReceivedTopic:
  Type: AWS::SNS::Topic
  Properties:
    DisplayName: Contribution Received
    TopicName: Contribution-Received
    KmsMasterKeyId: !Ref SNSKey
    Subscription:
      - Endpoint: !Ref AdminEmail
        Protocol: email
