{% for scope in ('Regional', 'CloudFront') %}
{{ scope }}Firewall:
  Type: AWS::WAFv2::WebACL
  Properties:
    Name: {{ scope }}FirewallPurplePay
    Description: Initial {{ scope }} WAF for PurplePay
    Scope: {{ scope | upper }}
    DefaultAction:
      Allow: {}
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: WAFPurplePay
    Rules:
      - Name: RuleWithAWSManagedRules
        Priority: 0
        OverrideAction:
          Count: {}
        VisibilityConfig:
          MetricName: RuleWithAWSManagedRulesMetric
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
        Statement:
          ManagedRuleGroupStatement:
            Name: AWSManagedRulesCommonRuleSet
            VendorName: AWS
            ExcludedRules: []
      - Name: BlockXssAttack
        Priority: 1
        Action:
          Block: {}
        VisibilityConfig:
          MetricName: BlockXssAttackMetric
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
        Statement:
          XssMatchStatement:
            FieldToMatch:
              AllQueryArguments: {}
            TextTransformations:
              - Priority: 1
                Type: NONE
{% endfor %}
