Gateway4xxErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    ActionsEnabled: true
    AlarmName: !Sub Gateway4xxErrors-${Product}-${LambdaRunEnvironment}
    AlarmDescription: !Sub Alarms when the ${Domain} API gateways return 4xx errors
    Dimensions:
      - Name: ApiName
        Value: !Sub ${Domain}-backend-${LambdaRunEnvironment}
    AlarmActions:
      - !Ref GatewayAlarmTopic
    MetricName: 4XXErrors
    Namespace: AWS/ApiGateway
    ComparisonOperator: GreaterThanOrEqualToThreshold
    EvaluationPeriods: 5
    Period: 60
    Statistic: Average
    Threshold: 0.3
    TreatMissingData: notBreaching
