Gateway4xxErrorTopic:
  Type: AWS::SNS::Topic
  Properties:
    DisplayName: !Sub Gateway4xxError-${Domain}-${LambdaRunEnvironment}
    TopicName: !Sub Gateway-Errors-4xx-${Domain}-${LambdaRunEnvironment}
    KmsMasterKeyId: !Ref SNSKey
    Subscription:
      - Endpoint: !Ref AdminEmail
        Protocol: email

Gateway4xxErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: Gateway4xxErrors
    AlarmDescription: !Sub Alarms when the ${Domain} API gateways return 4xx errors
    Dimensions:
      - Name: ApiName
        Value: !Sub ${Domain}-backend-${LambdaRunEnvironment}
    AlarmActions:
      - !Ref Gateway4xxErrorTopic
    MetricName: 4XXError
    Namespace: AWS/ApiGateway
    ComparisonOperator: GreaterThanOrEqualToThreshold
    EvaluationPeriods: 1
    Period: 300
    Statistic: Sum
    Threshold: 1
