GatewayLatencyP50Alarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub GatewayP50Timeout-${Product}-${LambdaRunEnvironment}
    AlarmDescription: !Sub Alarms when the ${Domain} latency P50 is too high
    ActionsEnabled: true
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: ApiName
        Value: !Sub ${Domain}-backend-${LambdaRunEnvironment}
    EvaluationPeriods: 5
    MetricName: Latency
    Namespace: AWS/ApiGateway
    Period: 60
    ExtendedStatistic: p50
    Threshold: 200
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref GatewayAlarmTopic

GatewayLatencyP90Alarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub GatewayP90Timeout-${Product}-${LambdaRunEnvironment}
    AlarmDescription: !Sub Alarms when the ${Domain} latency P90 is too high
    ActionsEnabled: true
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: ApiName
        Value: !Sub ${Domain}-backend-${LambdaRunEnvironment}
    EvaluationPeriods: 5
    MetricName: Latency
    Namespace: AWS/ApiGateway
    Period: 60
    ExtendedStatistic: p90
    Threshold: 2000
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref GatewayAlarmTopic
