PolicapitalGateway5xxErrorTopic:
  Type: AWS::SNS::Topic
  Properties:
    DisplayName: !Sub ${LambdaRunEnvironment}-${Domain}-Gateway5xxError
    TopicName: !Sub ${LambdaRunEnvironment}-${Domain}-Gateway-Errors-5xx
    KmsMasterKeyId: !Ref SNSKey
    Subscription:
      - Endpoint: !Ref AdminEmail
        Protocol: email

PolicapitalGateway5xxErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${LambdaRunEnvironment}-${Domain}-PolicapitalGateway5xxErrors
    AlarmDescription: !Sub Alarms when the ${Domain} Policapital gateway returns a 5xx error.
    Dimensions:
      - Name: ApiName
        Value: !Sub ${Domain}-backend-${LambdaRunEnvironment}
    AlarmActions:
      - !Ref PolicapitalGateway5xxErrorTopic
    MetricName: 5XXError
    Namespace: AWS/ApiGateway
    ComparisonOperator: GreaterThanOrEqualToThreshold
    EvaluationPeriods: 1
    Period: 300
    Statistic: Sum
    Threshold: 1
