BillableEvents:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    SSESpecification:
      SSEEnabled: true
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    ProvisionedThroughput:
      WriteCapacityUnits: 3
      ReadCapacityUnits: 3
    AttributeDefinitions:
      - AttributeName: committeeId
        AttributeType: S
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: committeeId
      - KeyType: RANGE
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
