Donors:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: !Sub donors-${LambdaRunEnvironment}
    SSESpecification:
      SSEEnabled: true
    ProvisionedThroughput:
      WriteCapacityUnits: 1
      ReadCapacityUnits: 1
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: id
    StreamSpecification:
      StreamViewType: NEW_IMAGE
