Donors:
  Type: AWS::DynamoDB::Table
  Properties:
    SSESpecification:
      SSEEnabled: true
    ProvisionedThroughput:
      WriteCapacityUnits: 1
      ReadCapacityUnits: 1
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: flacspeeMatch
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: id
      - KeyType: RANGE
        AttributeName: flacspeeMatch
    StreamSpecification:
      StreamViewType: NEW_IMAGE

