Rules:
  Type: AWS::DynamoDB::Table
  Properties:
    SSESpecification:
      SSEEnabled: true
    ProvisionedThroughput:
      WriteCapacityUnits: 1
      ReadCapacityUnits: 1
    AttributeDefinitions:
      - AttributeName: code
        AttributeType: S
    KeySchema:
      - KeyType: HASH
        AttributeName: code
    StreamSpecification:
      StreamViewType: NEW_IMAGE
