export const data = [
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 20,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 20,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 100,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 150,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 1300,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 50,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 25,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 25,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 25,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 25,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 100,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Andres",
    lastName: "Carpenter",
    employer: "Ullrich, Corkery and Kuhlman",
    addressLine1: "209 S. Cottage Street",
    addressLine2: "",
    city: "Woodside",
    state: "NY",
    postalCode: 11377,
    amount: 49,
    creditCardNumber: 341000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 20,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 30,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 25,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 100,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 100,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 1500,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 20,
    creditCardNumber: 344000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Eula",
    lastName: "Richards",
    employer: "Ratke, Ritchie and Cartwright",
    addressLine1: "9931 Cambridge Drive",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11211,
    amount: 250,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Rachel",
    lastName: "Porter",
    employer: "O'Reilly and Sons",
    addressLine1: "722 Cherry Hill St.",
    addressLine2: "",
    city: "Jamaica",
    state: "NY",
    postalCode: 11434,
    amount: 25,
    creditCardNumber: 349000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Rachel",
    lastName: "Porter",
    employer: "O'Reilly and Sons",
    addressLine1: "722 Cherry Hill St.",
    addressLine2: "",
    city: "Jamaica",
    state: "NY",
    postalCode: 11434,
    amount: 25,
    creditCardNumber: 349000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Rachel",
    lastName: "Porter",
    employer: "O'Reilly and Sons",
    addressLine1: "722 Cherry Hill St.",
    addressLine2: "",
    city: "Jamaica",
    state: "NY",
    postalCode: 11434,
    amount: 25,
    creditCardNumber: 349000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ron",
    lastName: "Lowe",
    employer: "Kuvalis, Ledner and Roberts",
    addressLine1: "144 Prospect Ave.",
    addressLine2: "",
    city: "Rego Park",
    state: "NY",
    postalCode: 11374,
    amount: 500,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ron",
    lastName: "Lowe",
    employer: "Kuvalis, Ledner and Roberts",
    addressLine1: "144 Prospect Ave.",
    addressLine2: "",
    city: "Rego Park",
    state: "NY",
    postalCode: 11374,
    amount: 1200,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ron",
    lastName: "Lowe",
    employer: "Kuvalis, Ledner and Roberts",
    addressLine1: "144 Prospect Ave.",
    addressLine2: "",
    city: "Rego Park",
    state: "NY",
    postalCode: 11374,
    amount: 3000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Flora",
    lastName: "Torres",
    employer: "Green, Pacocha and McCullough",
    addressLine1: "7 Summerhouse Dr.",
    addressLine2: "",
    city: "Newburgh",
    state: "NY",
    postalCode: 12550,
    amount: 4000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Flora",
    lastName: "Torres",
    employer: "Green, Pacocha and McCullough",
    addressLine1: "7 Summerhouse Dr.",
    addressLine2: "",
    city: "Newburgh",
    state: "NY",
    postalCode: 12550,
    amount: 250,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Flora",
    lastName: "Torres",
    employer: "Green, Pacocha and McCullough",
    addressLine1: "7 Summerhouse Dr.",
    addressLine2: "",
    city: "Newburgh",
    state: "NY",
    postalCode: 12550,
    amount: 250,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Matt",
    lastName: "Bryan",
    employer: "Renner-Heidenreich",
    addressLine1: "556 San Carlos Street",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11206,
    amount: 500,
    creditCardNumber: 374000000000000,
    expirationMonth: 3,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Matt",
    lastName: "Bryan",
    employer: "Renner-Heidenreich",
    addressLine1: "556 San Carlos Street",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11206,
    amount: 500,
    creditCardNumber: 374000000000000,
    expirationMonth: 3,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Matt",
    lastName: "Bryan",
    employer: "Renner-Heidenreich",
    addressLine1: "556 San Carlos Street",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11206,
    amount: 500,
    creditCardNumber: 374000000000000,
    expirationMonth: 3,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Taylor",
    lastName: "Jordan",
    employer: "Lemke, Paucek and Morar",
    addressLine1: "8882 Southampton Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10463,
    amount: 25,
    creditCardNumber: 344000000000000,
    expirationMonth: 3,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Taylor",
    lastName: "Jordan",
    employer: "Lemke, Paucek and Morar",
    addressLine1: "8882 Southampton Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10463,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "twitter",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Taylor",
    lastName: "Jordan",
    employer: "Lemke, Paucek and Morar",
    addressLine1: "8882 Southampton Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10463,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bernard",
    lastName: "Powell",
    employer: "Schimmel LLC",
    addressLine1: "319 Lyme Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10472,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "twitter",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bernard",
    lastName: "Powell",
    employer: "Schimmel LLC",
    addressLine1: "319 Lyme Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10472,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bernard",
    lastName: "Powell",
    employer: "Schimmel LLC",
    addressLine1: "319 Lyme Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10472,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kerry",
    lastName: "Mitchell",
    employer: "King and Sons",
    addressLine1: "7998 Wagon St.",
    addressLine2: "",
    city: "Forest Hills",
    state: "NY",
    postalCode: 11375,
    amount: 25,
    creditCardNumber: 341000000000000,
    expirationMonth: 5,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kerry",
    lastName: "Mitchell",
    employer: "King and Sons",
    addressLine1: "7998 Wagon St.",
    addressLine2: "",
    city: "Forest Hills",
    state: "NY",
    postalCode: 11375,
    amount: 40,
    creditCardNumber: 341000000000000,
    expirationMonth: 5,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kerry",
    lastName: "Mitchell",
    employer: "King and Sons",
    addressLine1: "7998 Wagon St.",
    addressLine2: "",
    city: "Forest Hills",
    state: "NY",
    postalCode: 11375,
    amount: 15,
    creditCardNumber: 341000000000000,
    expirationMonth: 5,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Janis",
    lastName: "Bishop",
    employer: "Stark, Turcotte and Bogisich",
    addressLine1: "249 East Elmwood Circle",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10023,
    amount: 25,
    creditCardNumber: 372000000000000,
    expirationMonth: 6,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Janis",
    lastName: "Bishop",
    employer: "Stark, Turcotte and Bogisich",
    addressLine1: "249 East Elmwood Circle",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10023,
    amount: 20,
    creditCardNumber: 372000000000000,
    expirationMonth: 6,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Janis",
    lastName: "Bishop",
    employer: "Stark, Turcotte and Bogisich",
    addressLine1: "249 East Elmwood Circle",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10023,
    amount: 20,
    creditCardNumber: 372000000000000,
    expirationMonth: 6,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Louis",
    lastName: "Palmer",
    employer: "Treutel, Ziemann and Osinski",
    addressLine1: "95 Jackson Avenue",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11223,
    amount: 10,
    creditCardNumber: 342000000000000,
    expirationMonth: 1,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Louis",
    lastName: "Palmer",
    employer: "Treutel, Ziemann and Osinski",
    addressLine1: "95 Jackson Avenue",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11223,
    amount: 10,
    creditCardNumber: 342000000000000,
    expirationMonth: 1,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jonathan",
    lastName: "Wilson",
    employer: "Huel, Bruen and Grady",
    addressLine1: "854 Swanson Ave.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11218,
    amount: 50,
    creditCardNumber: 370000000000000,
    expirationMonth: 4,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jonathan",
    lastName: "Wilson",
    employer: "Huel, Bruen and Grady",
    addressLine1: "854 Swanson Ave.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11218,
    amount: 50,
    creditCardNumber: 370000000000000,
    expirationMonth: 4,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Barbara",
    lastName: "Goodwin",
    employer: "Johnston, Ankunding and Champlin",
    addressLine1: "346 Big Rock Cove Road",
    addressLine2: "",
    city: "Staten Island",
    state: "NY",
    postalCode: 10306,
    amount: 100,
    creditCardNumber: 345000000000000,
    expirationMonth: 12,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Barbara",
    lastName: "Goodwin",
    employer: "Johnston, Ankunding and Champlin",
    addressLine1: "346 Big Rock Cove Road",
    addressLine2: "",
    city: "Staten Island",
    state: "NY",
    postalCode: 10306,
    amount: 100,
    creditCardNumber: 345000000000000,
    expirationMonth: 12,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sue",
    lastName: "Allen",
    employer: "Bartoletti-Becker",
    addressLine1: "986 Acacia Court",
    addressLine2: "",
    city: "East Elmhurst",
    state: "NY",
    postalCode: 11370,
    amount: 500,
    creditCardNumber: 371000000000000,
    expirationMonth: 12,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sue",
    lastName: "Allen",
    employer: "Bartoletti-Becker",
    addressLine1: "986 Acacia Court",
    addressLine2: "",
    city: "East Elmhurst",
    state: "NY",
    postalCode: 11370,
    amount: 500,
    creditCardNumber: 371000000000000,
    expirationMonth: 12,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jose",
    lastName: "Haynes",
    employer: "Abernathy-Lockman",
    addressLine1: "26 S. Church Court",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10002,
    amount: 1500,
    creditCardNumber: 375000000000000,
    expirationMonth: 2,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jose",
    lastName: "Haynes",
    employer: "Abernathy-Lockman",
    addressLine1: "26 S. Church Court",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10002,
    amount: 1500,
    creditCardNumber: 375000000000000,
    expirationMonth: 2,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Doug",
    lastName: "Brock",
    employer: "Parker-Wunsch",
    addressLine1: "351 Ramblewood Street",
    addressLine2: "",
    city: "Freeport",
    state: "NY",
    postalCode: 11520,
    amount: 20,
    creditCardNumber: 379000000000000,
    expirationMonth: 10,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Clara",
    lastName: "Olson",
    employer: "Heaney, Bruen and Kihn",
    addressLine1: "744 College Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10453,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sonia",
    lastName: "Norton",
    employer: "Romaguera, Hand and Monahan",
    addressLine1: "78 East La Sierra Avenue",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10032,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Cedric",
    lastName: "Clarke",
    employer: "Zieme-Kerluke",
    addressLine1: "151 West Fawn Drive",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10029,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Joanna",
    lastName: "Baker",
    employer: "Predovic-Erdman",
    addressLine1: "7573 Brook Lane",
    addressLine2: "",
    city: "Webster",
    state: "NY",
    postalCode: 14580,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kelli",
    lastName: "Murphy",
    employer: "Mante-Kris",
    addressLine1: "4 Pennington St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10011,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Neal",
    lastName: "Wells",
    employer: "Thompson, Ondricka and Hills",
    addressLine1: "45 Spring St.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11216,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Celia",
    lastName: "Castro",
    employer: "Gulgowski and Sons",
    addressLine1: "7059 Rosewood Road",
    addressLine2: "",
    city: "Poughkeepsie",
    state: "NY",
    postalCode: 12603,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Conrad",
    lastName: "Warner",
    employer: "Rolfson, Hudson and West",
    addressLine1: "96 Tailwater Court",
    addressLine2: "",
    city: "Fresh Meadows",
    state: "NY",
    postalCode: 11365,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Hugh",
    lastName: "Garrett",
    employer: "Crona-Nitzsche",
    addressLine1: "590 Lakewood Dr.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10462,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Marco",
    lastName: "Fowler",
    employer: "Schmidt-Tillman",
    addressLine1: "740 Henry Smith Drive",
    addressLine2: "",
    city: "Poughkeepsie",
    state: "NY",
    postalCode: 12601,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Francis",
    lastName: "Roberts",
    employer: "Schiller Inc",
    addressLine1: "347 West Sunbeam Drive",
    addressLine2: "",
    city: "Levittown",
    state: "NY",
    postalCode: 11756,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Otis",
    lastName: "Wilkins",
    employer: "Tremblay, Medhurst and Harvey",
    addressLine1: "24 Marconi St.",
    addressLine2: "",
    city: "South Richmond Hill",
    state: "NY",
    postalCode: 11419,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ada",
    lastName: "Maldonado",
    employer: "VonRueden LLC",
    addressLine1: "745 Rosewood St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10016,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sherry",
    lastName: "Rivera",
    employer: "Blanda-Rodriguez",
    addressLine1: "323 SE. Plumb Branch Street",
    addressLine2: "",
    city: "Massapequa",
    state: "NY",
    postalCode: 11758,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ernesto",
    lastName: "Moody",
    employer: "Jones PLC",
    addressLine1: "9933 Glenholme Rd.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10025,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "kickoff-fundraiser",
    paymentMethod: "check",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jeannette",
    lastName: "Bradley",
    employer: "Hettinger PLC",
    addressLine1: "8136 Ryan Drive",
    addressLine2: "",
    city: "Astoria",
    state: "NY",
    postalCode: 11105,
    amount: 500,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Lynne",
    lastName: "Dennis",
    employer: "Moore-Champlin",
    addressLine1: "438 Tarkiln Hill St.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11229,
    amount: 10,
    creditCardNumber: 345000000000000,
    expirationMonth: 3,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Billy",
    lastName: "Yates",
    employer: "Lehner-Heaney",
    addressLine1: "8930 Logan Dr.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10469,
    amount: 15,
    creditCardNumber: 373000000000000,
    expirationMonth: 4,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Edith",
    lastName: "Hodges",
    employer: "Schiller and Sons",
    addressLine1: "9275 Piper Court",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10028,
    amount: 20,
    creditCardNumber: 345000000000000,
    expirationMonth: 5,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sheri",
    lastName: "Wise",
    employer: "Swaniawski, Torp and Johns",
    addressLine1: "655 Pheasant Ave.",
    addressLine2: "",
    city: "West Babylon",
    state: "NY",
    postalCode: 11704,
    amount: 10,
    creditCardNumber: 349000000000000,
    expirationMonth: 6,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Lillian",
    lastName: "Dixon",
    employer: "Purdy and Sons",
    addressLine1: "614 Peachtree St.",
    addressLine2: "",
    city: "Patchogue",
    state: "NY",
    postalCode: 11772,
    amount: 10,
    creditCardNumber: 350000000000000,
    expirationMonth: 4,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Hazel",
    lastName: "Nash",
    employer: "Swift Ltd",
    addressLine1: "13 Central St.",
    addressLine2: "",
    city: "Hempstead",
    state: "NY",
    postalCode: 11550,
    amount: 10,
    creditCardNumber: 343000000000000,
    expirationMonth: 4,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Hilda",
    lastName: "Burgess",
    employer: "Turcotte, Effertz and Kshlerin",
    addressLine1: "47 Tower Dr.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10457,
    amount: 10,
    creditCardNumber: 375000000000000,
    expirationMonth: 3,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Vicky",
    lastName: "Adams",
    employer: "Stiedemann, Cummings and Padberg",
    addressLine1: "805 NE. Sycamore Street",
    addressLine2: "",
    city: "Lockport",
    state: "NY",
    postalCode: 14094,
    amount: 10,
    creditCardNumber: 344000000000000,
    expirationMonth: 7,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Donald",
    lastName: "Cummings",
    employer: "Gibson Ltd",
    addressLine1: "141 Bayberry Street",
    addressLine2: "",
    city: "Troy",
    state: "NY",
    postalCode: 12180,
    amount: 10,
    creditCardNumber: 372000000000000,
    expirationMonth: 5,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Cecil",
    lastName: "Boyd",
    employer: "Turcotte-Hettinger",
    addressLine1: "65 Pine Rd.",
    addressLine2: "",
    city: "South Ozone Park",
    state: "NY",
    postalCode: 11420,
    amount: 10,
    creditCardNumber: 374000000000000,
    expirationMonth: 3,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jessie",
    lastName: "Brady",
    employer: "O'Keefe Ltd",
    addressLine1: "5 Tallwood Rd.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11224,
    amount: 10,
    creditCardNumber: 348000000000000,
    expirationMonth: 7,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Isabel",
    lastName: "Hanson",
    employer: "Glover, Pacocha and Cruickshank",
    addressLine1: "70 Grand Avenue",
    addressLine2: "",
    city: "Elmont",
    state: "NY",
    postalCode: 11003,
    amount: 10,
    creditCardNumber: 373000000000000,
    expirationMonth: 8,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bobbie",
    lastName: "Osborne",
    employer: "Kuhlman-Halvorson",
    addressLine1: "24 Wall Rd.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10466,
    amount: 10,
    creditCardNumber: 372000000000000,
    expirationMonth: 9,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Melanie",
    lastName: "Abbott",
    employer: "Carroll-Pfeffer",
    addressLine1: "9070 Winding Way St.",
    addressLine2: "",
    city: "Lindenhurst",
    state: "NY",
    postalCode: 11757,
    amount: 10,
    creditCardNumber: 340000000000000,
    expirationMonth: 8,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Tara",
    lastName: "Buchanan",
    employer: "Abbott-Conn",
    addressLine1: "406 N. Pierce Street",
    addressLine2: "",
    city: "Rome",
    state: "NY",
    postalCode: 13440,
    amount: 10,
    creditCardNumber: 345000000000000,
    expirationMonth: 5,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Sean",
    lastName: "Ryan",
    employer: "Kunze and Sons",
    addressLine1: "313 North Shady Drive",
    addressLine2: "",
    city: "Middletown",
    state: "NY",
    postalCode: 10940,
    amount: 10,
    creditCardNumber: 342000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Spencer",
    lastName: "Mills",
    employer: "Flatley LLC",
    addressLine1: "7025 Brook Court",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11208,
    amount: 10,
    creditCardNumber: 373000000000000,
    expirationMonth: 1,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Paulette",
    lastName: "Strickland",
    employer: "Nolan, Zemlak and Frami",
    addressLine1: "45 York Dr.",
    addressLine2: "",
    city: "Auburn",
    state: "NY",
    postalCode: 13021,
    amount: 10,
    creditCardNumber: 344000000000000,
    expirationMonth: 1,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kendra",
    lastName: "Love",
    employer: "Hodkiewicz and Sons",
    addressLine1: "8599 Tower Rd.",
    addressLine2: "",
    city: "Endicott",
    state: "NY",
    postalCode: 13760,
    amount: 10,
    creditCardNumber: 344000000000000,
    expirationMonth: 10,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Pablo",
    lastName: "Richardson",
    employer: "Auer, Gleichner and Christiansen",
    addressLine1: "8310 Clay Dr.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10452,
    amount: 10,
    creditCardNumber: 379000000000000,
    expirationMonth: 12,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Robin",
    lastName: "Lynch",
    employer: "Crooks-Thiel",
    addressLine1: "72 Nichols St.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11221,
    amount: 10,
    creditCardNumber: 371000000000000,
    expirationMonth: 12,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Rebecca",
    lastName: "Hansen",
    employer: "Price and Sons",
    addressLine1: "9734 West Blackburn Ave.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10460,
    amount: 10,
    creditCardNumber: 349000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Emma",
    lastName: "Cobb",
    employer: "Schulist Group",
    addressLine1: "8131 Wentworth St.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11212,
    amount: 10,
    creditCardNumber: 345000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Laurence",
    lastName: "Tate",
    employer: "Wunsch, Jenkins and Hansen",
    addressLine1: "9504 Old York Ave.",
    addressLine2: "",
    city: "Far Rockaway",
    state: "NY",
    postalCode: 11691,
    amount: 10,
    creditCardNumber: 373000000000000,
    expirationMonth: 4,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Frankie",
    lastName: "Thomas",
    employer: "Hauck-Trantow",
    addressLine1: "838 Cedar Swamp St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10003,
    amount: 10,
    creditCardNumber: 347000000000000,
    expirationMonth: 7,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ernest",
    lastName: "Austin",
    employer: "Zulauf-Hudson",
    addressLine1: "318 Oak Ave.",
    addressLine2: "",
    city: "Staten Island",
    state: "NY",
    postalCode: 10312,
    amount: 100,
    creditCardNumber: 5380000000000000,
    expirationMonth: 4,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ebony",
    lastName: "Perry",
    employer: "Nolan-Cronin",
    addressLine1: "47 Wagon Dr.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11201,
    amount: 100,
    creditCardNumber: 5370000000000000,
    expirationMonth: 3,
    expirationYear: 2026,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Silvia",
    lastName: "Sparks",
    employer: "Lind Inc",
    addressLine1: "8757 Wagon Drive",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10040,
    amount: 100,
    creditCardNumber: 5420000000000000,
    expirationMonth: 7,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Elaine",
    lastName: "Rhodes",
    employer: "Haag Group",
    addressLine1: "1 Edgewood Lane",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11214,
    amount: 100,
    creditCardNumber: 5430000000000000,
    expirationMonth: 8,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Debra",
    lastName: "Matthews",
    employer: "Reichert-Zboncak",
    addressLine1: "59 Bridle Street",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10473,
    amount: 100,
    creditCardNumber: 5540000000000000,
    expirationMonth: 10,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kellie",
    lastName: "Chapman",
    employer: "Hilpert Group",
    addressLine1: "9604 Foster St.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10456,
    amount: 100,
    creditCardNumber: 5280000000000000,
    expirationMonth: 9,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Carroll",
    lastName: "Fisher",
    employer: "Larkin, Lakin and Olson",
    addressLine1: "1 Mulberry Court",
    addressLine2: "",
    city: "Hamburg",
    state: "NY",
    postalCode: 10475,
    amount: 100,
    creditCardNumber: 5180000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Dennis",
    lastName: "Campbell",
    employer: "Kilback Group",
    addressLine1: "485 Brickyard St.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10461,
    amount: 100,
    creditCardNumber: 5260000000000000,
    expirationMonth: 4,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Adrian",
    lastName: "Ortiz",
    employer: "Gottlieb-Waelchi",
    addressLine1: "886 NE. Cedar Swamp Road",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11219,
    amount: 100,
    creditCardNumber: 5310000000000000,
    expirationMonth: 6,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jesse",
    lastName: "Hill",
    employer: "Schneider Group",
    addressLine1: "9740 Sycamore St.",
    addressLine2: "",
    city: "Flushing",
    state: "NY",
    postalCode: 11355,
    amount: 100,
    creditCardNumber: 5170000000000000,
    expirationMonth: 5,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Stella",
    lastName: "Greene",
    employer: "Rau, Fay and Zieme",
    addressLine1: "879 Inverness Street",
    addressLine2: "",
    city: "Westbury",
    state: "NY",
    postalCode: 11590,
    amount: 100,
    creditCardNumber: 5280000000000000,
    expirationMonth: 4,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Shari",
    lastName: "Owen",
    employer: "Toy-Nitzsche",
    addressLine1: "56 Princeton Dr.",
    addressLine2: "",
    city: "Buffalo",
    state: "NY",
    postalCode: 14215,
    amount: 100,
    creditCardNumber: 5330000000000000,
    expirationMonth: 2,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Joan",
    lastName: "Gonzalez",
    employer: "Ritchie-Goodwin",
    addressLine1: "953 Bow Ridge Rd.",
    addressLine2: "",
    city: "Rochester",
    state: "NY",
    postalCode: 14609,
    amount: 100,
    creditCardNumber: 5210000000000000,
    expirationMonth: 1,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Erma",
    lastName: "Thompson",
    employer: "Unemployed",
    addressLine1: "9620 Prospect St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10024,
    amount: 100,
    creditCardNumber: 5390000000000000,
    expirationMonth: 1,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "William",
    lastName: "Garcia",
    employer: "Unemployed",
    addressLine1: "4 Old York Avenue",
    addressLine2: "",
    city: "Astoria",
    state: "NY",
    postalCode: 11103,
    amount: 100,
    creditCardNumber: 5440000000000000,
    expirationMonth: 12,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Nicolas",
    lastName: "Fowler",
    employer: "Unemployed",
    addressLine1: "9375 Orange Ave.",
    addressLine2: "",
    city: "Buffalo",
    state: "NY",
    postalCode: 14224,
    amount: 20,
    creditCardNumber: 5290000000000000,
    expirationMonth: 5,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Myrtle",
    lastName: "Ferguson",
    employer: "Unemployed",
    addressLine1: "7316 Airport Road",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11204,
    amount: 10,
    creditCardNumber: 5580000000000000,
    expirationMonth: 6,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Wilfred",
    lastName: "Welch",
    employer: "Retired",
    addressLine1: "9947 Tailwater Street",
    addressLine2: "",
    city: "Jamaica",
    state: "NY",
    postalCode: 11432,
    amount: 15,
    creditCardNumber: 5440000000000000,
    expirationMonth: 7,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ricky",
    lastName: "Walton",
    employer: "Retired",
    addressLine1: "74 W. Jennings St.",
    addressLine2: "",
    city: "Staten Island",
    state: "NY",
    postalCode: 10314,
    amount: 14,
    creditCardNumber: 5250000000000000,
    expirationMonth: 8,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Molly",
    lastName: "Nash",
    employer: "Retired",
    addressLine1: "917 Smith Store Rd.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11207,
    amount: 12,
    creditCardNumber: 5120000000000000,
    expirationMonth: 8,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Roberta",
    lastName: "Holloway",
    employer: "Retired",
    addressLine1: "343 Virginia Road",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11228,
    amount: 11,
    creditCardNumber: 5540000000000000,
    expirationMonth: 12,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Terri",
    lastName: "Briggs",
    employer: "Retired",
    addressLine1: "44 Fawn Avenue",
    addressLine2: "",
    city: "Brentwood",
    state: "NY",
    postalCode: 11717,
    amount: 10,
    creditCardNumber: 5250000000000000,
    expirationMonth: 11,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Matt",
    lastName: "Harper",
    employer: "Retired",
    addressLine1: "37 Tunnel Dr.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11234,
    amount: 5,
    creditCardNumber: 5280000000000000,
    expirationMonth: 3,
    expirationYear: 2026,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Carol",
    lastName: "Page",
    employer: "Retired",
    addressLine1: "13 W. Sage St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10009,
    amount: 5,
    creditCardNumber: 5390000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Mindy",
    lastName: "Mccarthy",
    employer: "Retired",
    addressLine1: "8542 South School Street",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11237,
    amount: 5,
    creditCardNumber: 5170000000000000,
    expirationMonth: 2,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Fernando",
    lastName: "Reyes",
    employer: "Retired",
    addressLine1: "84 Eagle St.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10465,
    amount: 5,
    creditCardNumber: 5570000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Simon",
    lastName: "Jacobs",
    employer: "Retired",
    addressLine1: "59 College St.",
    addressLine2: "",
    city: "Buffalo",
    state: "NY",
    postalCode: 14221,
    amount: 5,
    creditCardNumber: 5590000000000000,
    expirationMonth: 10,
    expirationYear: 2025,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kristin",
    lastName: "Dean",
    employer: "Retired",
    addressLine1: "889 Lees Creek Court",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10451,
    amount: 10,
    creditCardNumber: 5310000000000000,
    expirationMonth: 11,
    expirationYear: 2026,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Leon",
    lastName: "Rice",
    employer: "Retired",
    addressLine1: "93 Mammoth Street",
    addressLine2: "",
    city: "Jamaica",
    state: "NY",
    postalCode: 11435,
    amount: 10,
    creditCardNumber: 5210000000000000,
    expirationMonth: 12,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Latoya",
    lastName: "Little",
    employer: "Retired",
    addressLine1: "324 Deerfield Ave.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10034,
    amount: 50,
    creditCardNumber: 5150000000000000,
    expirationMonth: 10,
    expirationYear: 2024,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kristy",
    lastName: "Steele",
    employer: "Retired",
    addressLine1: "793 Overlook St.",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10128,
    amount: 2000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Terrance",
    lastName: "Clarke",
    employer: "Retired",
    addressLine1: "70 Longfellow St.",
    addressLine2: "",
    city: "Spring Valley",
    state: "NY",
    postalCode: 10977,
    amount: 250,
    creditCardNumber: 5300000000000000,
    expirationMonth: 6,
    expirationYear: 2023,
    refCode: "twitter",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Patty",
    lastName: "Lamb",
    employer: "Retired",
    addressLine1: "15 Williams Ave.",
    addressLine2: "",
    city: "Ridgewood",
    state: "NY",
    postalCode: 11385,
    amount: 1500,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "home-page",
    paymentMethod: "ACH",
    contributorType: "fam",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Leland",
    lastName: "Bass",
    employer: "Retired",
    addressLine1: "93 Schoolhouse Street",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10033,
    amount: 10,
    creditCardNumber: 5120000000000000,
    expirationMonth: 7,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Marc",
    lastName: "Hopkins",
    employer: "Retired",
    addressLine1: "591 Carriage Court",
    addressLine2: "",
    city: "Astoria",
    state: "NY",
    postalCode: 11106,
    amount: 15,
    creditCardNumber: 5340000000000000,
    expirationMonth: 8,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jacob",
    lastName: "Nichols",
    employer: "Retired",
    addressLine1: "7053 Pulaski Rd.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11210,
    amount: 150,
    creditCardNumber: 378000000000000,
    expirationMonth: 9,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Minnie",
    lastName: "Elliott",
    employer: "Retired",
    addressLine1: "61 53rd St.",
    addressLine2: "",
    city: "Jamestown",
    state: "NY",
    postalCode: 14701,
    amount: 10,
    creditCardNumber: 379000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bethany",
    lastName: "Dawson",
    employer: "Retired",
    addressLine1: "277 Elizabeth St.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11233,
    amount: 10,
    creditCardNumber: 341000000000000,
    expirationMonth: 9,
    expirationYear: 2024,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Owen",
    lastName: "Goodwin",
    employer: "Retired",
    addressLine1: "5 South Albany Dr.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11236,
    amount: 5,
    creditCardNumber: 5370000000000000,
    expirationMonth: 7,
    expirationYear: 2023,
    refCode: "home-page",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Bryan",
    lastName: "Howard",
    employer: "Retired",
    addressLine1: "8 Old York St.",
    addressLine2: "",
    city: "Tonawanda",
    state: "NY",
    postalCode: 14150,
    amount: 5,
    creditCardNumber: 5240000000000000,
    expirationMonth: 5,
    expirationYear: 2025,
    refCode: "home-page",
    paymentMethod: "credit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "John",
    lastName: "Wright",
    employer: "Retired",
    addressLine1: "9065 South Greystone Ave.",
    addressLine2: "",
    city: "Bronx",
    state: "NY",
    postalCode: 10458,
    amount: 5,
    creditCardNumber: 5360000000000000,
    expirationMonth: 6,
    expirationYear: 2023,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Elisa",
    lastName: "Wright",
    employer: "Retired",
    addressLine1: "22 North Henry Street",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11230,
    amount: 5,
    creditCardNumber: 5170000000000000,
    expirationMonth: 2,
    expirationYear: 2025,
    refCode: "facebook",
    paymentMethod: "debit",
    contributorType: "ind",
    companyName: "",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "John",
    lastName: "Howard",
    employer: "",
    addressLine1: "9854 Inverness Dr.",
    addressLine2: "",
    city: "Brooklyn",
    state: "NY",
    postalCode: 11238,
    amount: 3000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "pac",
    companyName: "CRYPTO NOW PAC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jessica",
    lastName: "Jensen",
    employer: "",
    addressLine1: "377 Honey Creek Street",
    addressLine2: "",
    city: "Yonkers",
    state: "NY",
    postalCode: 10701,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "llc",
    companyName: "Cars for You LLC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Jackson",
    lastName: "Bastian",
    employer: "",
    addressLine1: "153 Bayport Ave.",
    addressLine2: "",
    city: "Ithaca",
    state: "NY",
    postalCode: 14850,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "llc",
    companyName: "Fast Hot Coffee LLC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Kelli",
    lastName: "Fresno",
    employer: "",
    addressLine1: "8062 Rockcrest St.",
    addressLine2: "",
    city: "Fairport",
    state: "NY",
    postalCode: 14450,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "llc",
    companyName: "Best Printing Company",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Latoya",
    lastName: "Tilda",
    employer: "",
    addressLine1: "9464 Devonshire Street",
    addressLine2: "",
    city: "Huntington Station",
    state: "NY",
    postalCode: 11746,
    amount: 2400,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "pac",
    companyName: "HOORAY PAC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Marco",
    lastName: "Hamson",
    employer: "",
    addressLine1: "9691 Mechanic Street",
    addressLine2: "",
    city: "New York",
    state: "NY",
    postalCode: 10027,
    amount: 1600,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "solep",
    companyName: "Hilltop Communications",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Flora",
    lastName: "Pionsco",
    employer: "",
    addressLine1: "801 Carson Ave.",
    addressLine2: "",
    city: "North Tonawanda",
    state: "NY",
    postalCode: 14120,
    amount: 1000,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "pac",
    companyName: "YOU GOT THIS PAC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
  {
    committeeId: "",
    firstName: "Ricky",
    lastName: "Peters",
    employer: "",
    addressLine1: "9049 Brewery Rd.",
    addressLine2: "",
    city: "Flushing",
    state: "NY",
    postalCode: 11354,
    amount: 4700,
    creditCardNumber: "",
    expirationMonth: "",
    expirationYear: "",
    refCode: "corporate-fundraiser",
    paymentMethod: "ACH",
    contributorType: "llc",
    companyName: "Morning Wire Treatment LLC",
    committeeType: "",
    cpfId: "",
    principalOfficerFirstName: "",
    principalOfficerMiddleName: "",
    principalOfficerLastName: "",
  },
];
