{% for site in ('dev', 'qa') %}
{{ site }}CloudFront:
  Type: AWS::CloudFront::Distribution
  Condition: Production
  Properties:
    DistributionConfig:
      Comment: !Sub Deployed via ${AWS::StackName}
      Enabled: true
      PriceClass: PriceClass_100
      HttpVersion: http2
      DefaultRootObject: index.html
      IPV6Enabled: true
      WebACLId: !GetAtt CloudFrontFirewall.Arn
      Aliases:
        - !Sub {{ site }}.${Domain}
      Origins:
        - Id: !Ref {{ site }}WebsiteBucket
          DomainName: !GetAtt {{ site }}WebsiteBucket.DomainName
          OriginPath: ''
          S3OriginConfig:
            OriginAccessIdentity:
              !Sub origin-access-identity/cloudfront/${OAIPurplePay}
          ConnectionAttempts: 3
          ConnectionTimeout: 10
        - Id: !Sub ${ {{ site }}WebsiteBucket }-us-west-1
          DomainName: !Sub ${ {{ site }}WebsiteBucket }-us-west-1.s3.us-west-1.amazonaws.com
          OriginPath: ''
          S3OriginConfig:
            OriginAccessIdentity:
              !Sub origin-access-identity/cloudfront/${OAIPurplePay}
          ConnectionAttempts: 3
          ConnectionTimeout: 10
      OriginGroups:
        Quantity: 1
        Items:
          - Id: s3_static_sites
            Members:
              Quantity: 2
              Items:
                - OriginId: !Ref {{ site }}WebsiteBucket
                - OriginId: !Sub ${ {{ site }}WebsiteBucket }-us-west-1
            FailoverCriteria:
              StatusCodes:
                Quantity: 6
                Items:
                  - 500
                  - 502
                  - 503
                  - 504
                  - 404
                  - 403
      DefaultCacheBehavior:
        ViewerProtocolPolicy: redirect-to-https
        TargetOriginId: !Ref {{ site }}WebsiteBucket
        Compress: true
        SmoothStreaming: false
        CachePolicyId: !Ref CachePolicy
        DefaultTTL: 60
        MinTTL: 0
        MaxTTL: 31536000
        AllowedMethods:
          - HEAD
          - GET
        CachedMethods:
          - HEAD
          - GET
        ForwardedValues:
          Cookies:
            Forward: all
          QueryString: true
          Headers: ['*']
        LambdaFunctionAssociations:
          - EventType: viewer-response
            LambdaFunctionARN: !GetAtt LambdaEdgeFunctionVersion.FunctionArn
      ViewerCertificate:
        AcmCertificateArn: !Ref CertificateManagerCertificate
        MinimumProtocolVersion: TLSv1.2_2019
        SslSupportMethod: sni-only
      Restrictions:
        GeoRestriction:
          RestrictionType: none
{% endfor %}
