DynamoDBsTemplate:
{% if REGION in ['us-east-1', 'us-west-2'] %}
  Type: AWS::CloudFormation::Stack
  Properties:
    TemplateURL: dynamodbs.yml
    TimeoutInMinutes: 60
    Parameters:
      LambdaRunEnvironment: !Ref LambdaRunEnvironment
      Product: !Ref Product
      BackupRegion: us-east-2
{% endif %}
