BankSyncFunction:
  Type: "AWS::Serverless::Function"
  Properties:
    FunctionName: !Sub ${AWS::StackName}-BankSyncFunction
    Runtime: nodejs14.x
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.bankSyncHandler
    Role: !GetAtt LambdaGraphQLRole.Arn
    Timeout: 40
    MemorySize: 300
    Events:
      EveryMinuteEvent:
        Type: Schedule
        Properties:
          Schedule: 'rate(5 minutes)'
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV:
          !Ref LambdaRunEnvironment
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName
        AGGREGATES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.AggregatesTableName
        DONORS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.DonorsTableName
        RULES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.RulesTableName
        BILLABLE_EVENTS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableName

BankSyncInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref BankSyncFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
