BluelinkFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-BluelinkFunction
    Description: API Endpoint for Bluelink data sync
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.bluelink
    Runtime: nodejs14.x
    Role: !GetAtt LambdaGraphQLRole.Arn
    Timeout: 90
    MemorySize: 400
    Events:
      BluelinkEvent:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /api/platform/bluelink
          Method: post
          RestApiId: !Ref DonorGateway
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV:
          !Ref LambdaRunEnvironment
        CORS_ORIGIN:
          !Sub https://donate.${Domain}.${TLD}
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName
        AGGREGATES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.AggregatesTableName
        DONORS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.DonorsTableName
        RULES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.RulesTableName
        BILLABLE_EVENTS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableName

BluelinkInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref BluelinkFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
