CommitteeGraphQLFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-CommitteeGraphQLFunction
    Description: GraphQL API for Committees
    CodeUri: lambdas/
    MemorySize: 200
    Layers:
      - !Ref ServicesLayer
    Handler: app.committeeGraphQLHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaGraphQLRole.Arn
    Events:
      GraphQLAny:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /api/committee/graphql
          Method: ANY
          RestApiId: !Ref CommitteeGateway
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV:
          !Ref LambdaRunEnvironment
        CORS_ORIGIN:
          !Sub https://dashboard.${Domain}.${TLD}
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName
        DONORS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.DonorsTableName
        RULES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.RulesTableName
        BILLABLE_EVENTS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableName
        AUDIT_LOGS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.AuditLogsTableName

CommitteeGQLInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref CommitteeGraphQLFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
