DonationEmailerFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-DonationEmailer
    Description: Receive DynamoDB events and sends email with the transaction details
    CodeUri: services/emailer
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaSESRole.Arn
    Events:
      ContributionMade:
        Type: SQS
        Properties:
          BatchSize: 1
          Queue: !GetAtt EmailQueue.Arn
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
        POS_RECEIPT: !Sub ${ContributorReceiptTemplate.Outputs.SES}
        POS_RECORD: !Sub ${CommitteeReceiptTemplate.Outputs.SES}
