ExternalContribSQSFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-ExternalContribSQSFunction
    Description: Sync Transactions with an external contributions account
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.externalContribSQS
    Runtime: nodejs14.x
    Role: !GetAtt LambdaExternalDataRole.Arn
    Events:
      SyncInitiated:
        Type: SQS
        Properties:
          BatchSize: 1
          Queue: !GetAtt ExternalContribQueue.Arn
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName
        DONORS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.DonorsTableName
        RULES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.RulesTableName
        BILLABLE_EVENTS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableName

ExternalConfigSQSInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref ExternalContribSQSFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
