PolicapitalAnalyticsFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-PolicapitalAnalyticsFunction
    Description: Log Analytic data for Policapital Contribution activity
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.policapitalAnalyticsHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaBasicRole.Arn
    Events:
      PolicapitalAnalytics:
        Type: Api
        Properties:
          Path: /api/donor/analytics
          Method: post
          RestApiId: !Ref DonorGateway
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment

AnalyticsInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref PolicapitalAnalyticsFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
