PolicapitalEmailerFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-PolicapitalEmailerFunction
    Description: Receive DynamoDB events and sends email with the transaction details
    CodeUri: services/platform
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    Role: !Sub ${IAM.Outputs.LambdaSESRoleArn}
    Events:
      ContributionMade:
        Type: SQS
        Properties:
          BatchSize: 1
          Queue: !GetAtt EmailQueue.Arn
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
        POS_RECEIPT: !Sub ${ContributorReceiptTemplate.Outputs.SES}
        POS_RECORD: !Sub ${CommitteeReceiptTemplate.Outputs.SES}
