PolicapitalOnboardFunction:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  DeletionPolicy: Retain
  Properties:
    FunctionName: !Sub ${AWS::StackName}-PolicapitalOnboardFunction
    Description: Backend to onboard a committee to the Policapital platform
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.policapitalOnboardHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaBasicRole.Arn
    Events:
      Onboard:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /api/onboard
          Method: get
          RestApiId: !Ref DonorGateway
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment

OnboardInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref PolicapitalOnboardFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
