PolicapitalEmailerFunction:
  Type: AWS::Serverless::Function
  DeletionPolicy: Retain
  Properties:
    FunctionName: !Sub ${AWS::StackName}-PolicapitalEmailerFunction
    Description: Receive DynamoDB events and send email with the transaction details
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.policapitalEmailerHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaSESRole.Arn
    Events:
      ContributionMade:
        Type: SQS
        Properties:
          BatchSize: 1
          Queue: !GetAtt EmailQueue.Arn
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        NOTIFICATION_EMAIL_ADDRESS: !Ref NotificationEmailAddress
        RUNENV: !Ref LambdaRunEnvironment
        SES_CONFIG_SET: !Ref SESConfigSet
{% if REGION in ['us-east-1', 'us-west-2'] %}
        POS_RECEIPT: !Sub ${ContributorReceiptTemplate.Outputs.SES}
        POS_RECORD: !Sub ${CommitteeReceiptTemplate.Outputs.SES}
{% endif %}

EmailerInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref PolicapitalEmailerFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
