PolicapitalAnalyticsFunction:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    FunctionName: !Sub ${AWS::StackName}-PolicapitalAnalyticsFunction
    Description: Log Analytic data for Policapital Contribution activity
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.policapitalAnalyticsHandler
    Runtime: nodejs12.x
    Role: !GetAtt LambdaBasicRole.Arn
    Events:
      PolicapitalAnalytics:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /api/analytics
          Method: post
          RestApiId: !Ref DonationGateway
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
