StratoSQSFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-StratoQueueFunction
    Description: Commits transactions to a committee's chain on Strato
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.stratoSQS
    Runtime: nodejs14.x
    Role: !GetAtt LambdaGraphQLRole.Arn
    Events:
      TransactionVerified:
        Type: SQS
        Properties:
          BatchSize: 1
          Queue: !GetAtt StratoQueue.Arn
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName

StratoInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref StratoSQSFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
