StripeWebhookFunction:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    FunctionName: !Sub ${AWS::StackName}-StripeWebhookFunction
    Description: Stripe Webhook Endpoint
    CodeUri: lambdas/
    Layers:
      - !Ref ServicesLayer
    Handler: app.stripeWebhook
    Runtime: nodejs12.x
    Role: !GetAtt LambdaGraphQLRole.Arn
    Timeout: 50
    MemorySize: 200
    Events:
      PlatformContributeEvent:
        Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        Properties:
          Path: /api/platform/webhook
          Method: post
          RestApiId: !Ref DonorGateway
    DeadLetterQueue:
      TargetArn: !Ref LambdaDLQ
      Type: SNS
    Environment:
      Variables:
        RUNENV:
          !Ref LambdaRunEnvironment
        TRANSACTIONS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.TransactionsTableName
        COMMITTEES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.CommitteesTableName
        DONORS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.DonorsTableName
        RULES_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.RulesTableName
        BILLABLE_EVENTS_DDB_TABLE_NAME:
          !GetAtt DynamoDBsTemplate.Outputs.BillableEventsTableName

StripeWebhookInvokeConfig:
  Type: AWS::Lambda::EventInvokeConfig
  Properties:
    FunctionName: !Ref StripeWebhookFunction
    Qualifier: "$LATEST"
    MaximumRetryAttempts: 0
    DestinationConfig:
      OnSuccess:
        Destination: !Ref LambdaSuccessQueue
