TransactionEventDispatcherFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub ${AWS::StackName}-TransactionEventDispatcherFunction
    Description: Receive DynamoDB events and queues notifications with transaction details
    CodeUri: services/policapital/receiver
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    Role: !Sub ${IAM.Outputs.LambdaDonationReceiverRoleArn}
    Events:
      TransactionRecorded:
        Type: DynamoDB
        Properties:
          BatchSize: 1
          StartingPosition: LATEST
          Stream: !GetAtt Contributions.StreamArn
    Environment:
      Variables:
        RUNENV: !Ref LambdaRunEnvironment
        SQSQUEUE: !Ref EmailQueue
